const DB='sk-web-local', VER=1;
const stores=['personal','assets','novelties','parts','consumptions'];
let db;
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const uuid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const now=()=>new Date().toISOString();
function openDB(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{for(const s of stores)if(!r.result.objectStoreNames.contains(s))r.result.createObjectStore(s,{keyPath:'id'})};r.onsuccess=()=>{db=r.result;ok(db)};r.onerror=()=>no(r.error)})}
function all(store){return new Promise((ok,no)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function put(store,obj){return new Promise((ok,no)=>{const r=db.transaction(store,'readwrite').objectStore(store).put(obj);r.onsuccess=()=>ok(obj);r.onerror=()=>no(r.error)})}
const fd=f=>Object.fromEntries(new FormData(f).entries());
function mark(){return {id:uuid(),createdAt:now(),updatedAt:now(),syncState:'pending'}}
function letters(n){let s=''; do{s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)-1}while(n>=0);return s.padStart(3,'A')}
async function nextMark(){const a=await all('assets');let n=0;for(const x of a){if(/^[A-Z]{3}$/.test(x.marcaInterna||'')){const v=[...x.marcaInterna].reduce((z,c)=>z*26+c.charCodeAt(0)-65,0);n=Math.max(n,v+1)}}return letters(n)}
function assetLabel(a){return [a.clase,a.marcaInterna,a.serial,a.modelo&&`Mod. ${a.modelo}`,a.largo&&`${a.largo} ft`].filter(Boolean).join(' - ')}
function option(sel,value,text){const o=document.createElement('option');o.value=value;o.textContent=text;sel.append(o)}
async function refresh(){const [p,a,n,c]=await Promise.all(['personal','assets','novelties','consumptions'].map(all));$('#pCount').textContent=p.length;$('#aCount').textContent=a.length;$('#nCount').textContent=n.length;$('#cCount').textContent=c.length;
 $('#personalList').innerHTML=p.slice(-10).reverse().map(x=>`<div class="row"><b>${x.nombre}</b><small>${x.documento} · ${x.empresa} · ${x.cargo}</small></div>`).join('');
 $('#assetList').innerHTML=a.slice(-10).reverse().map(x=>`<div class="row"><b>${assetLabel(x)}</b><small>${x.ubicacion} · ${x.estado}${x.mina?' · '+x.mina:''}</small></div>`).join('');
 $('#noveltyList').innerHTML=n.slice(-10).reverse().map(x=>`<div class="row"><b>${x.descripcion}</b><small>${x.fechaLocal} · ${x.ubicacion} · ${x.estado}</small></div>`).join('');
 $('#consumptionList').innerHTML=c.slice(-10).reverse().map(x=>`<div class="row"><b>${x.nombreRepuesto} × ${x.cantidad}</b><small>${x.origen} · ${x.fechaLocal}</small></div>`).join('');
 for(const s of [$('#novAsset'),$('#conAsset')]){const old=s.value;s.innerHTML='<option value="">Seleccionar</option>';a.filter(x=>s!==$('#conAsset')||['yt','columna'].includes((x.clase||'').toLowerCase())).forEach(x=>option(s,x.id,assetLabel(x)));s.value=old}
 const r=$('#responsible');r.innerHTML='';const bode=p.filter(x=>['bodeguero','bodeguera'].includes((x.cargo||'').trim().toLowerCase()));bode.forEach(x=>option(r,x.id,`${x.documento} - ${x.nombre}`));const juan=bode.find(x=>x.documento==='1046903159'||/juan fernando echavarr[ií]a/i.test(x.nombre));if(juan)r.value=juan.id;
 await updateParts();}
async function updateNoveltyOptions(){const a=(await all('assets')).find(x=>x.id===$('#novAsset').value);const base=['Se asigna (si es nueva)','Se entrega (cuando es usada)','Sale fuera de mina a reparación','Sale trasladada a otra mina','Revista física','Encontrada abandonada','Dada de baja mediante acta'];if(a&&['yt','columna'].includes((a.clase||'').toLowerCase()))base.push('Ingresa a bodega superficie de reparación','Se devuelve reparada a mina de procedencia');$('#novDesc').innerHTML='';base.forEach(x=>option($('#novDesc'),x,x))}
async function updateParts(){if(!db)return;const parts=await all('parts'), origin=$('#origin').value.replace('YT','');$('#part').innerHTML='<option value="">Seleccionar</option>';parts.filter(x=>String(x.detalle)===origin).forEach(x=>option($('#part'),x.id,x.numero?`${x.numero} - ${x.nombre}`:x.nombre));$('#partNo').value='';$('#partName').value=''}
async function seedParts(){if((await all('parts')).length)return;for(const [detalle,numero,nombre] of [['28','', 'Lubricador'],['28','', 'Tapón lubricador'],['28','', 'Funda de revestimiento'],['29','', 'Lubricador'],['29','', 'Tapón lubricador'],['29','', 'Funda de revestimiento']])await put('parts',{...mark(),detalle,numero,nombre})}
$('#nav').addEventListener('click',e=>{if(!e.target.dataset.view)return;$$('#nav button').forEach(x=>x.classList.toggle('active',x===e.target));$$('.view').forEach(x=>x.classList.toggle('active',x.id===e.target.dataset.view))});
$('#personalForm').addEventListener('submit',async e=>{e.preventDefault();const x=fd(e.target),p=await all('personal');if(p.some(y=>y.documento.trim()===x.documento.trim()))return alert('Funcionario ya existe');await put('personal',{...mark(),...x});e.target.reset();await refresh()});
$('#assetForm').addEventListener('submit',async e=>{e.preventDefault();const x=fd(e.target),a=await all('assets');x.marcaInterna=await nextMark();x.consecutivo=String(a.length+1);x.ubicacion='Bodega de Superficie';await put('assets',{...mark(),...x});e.target.reset();await refresh();alert(`Activo registrado: ${x.marcaInterna}`)});
$('#novAsset').addEventListener('change',updateNoveltyOptions);
$('#noveltyForm').addEventListener('submit',async e=>{e.preventDefault();const x=fd(e.target),assets=await all('assets'),a=assets.find(y=>y.id===x.assetId);if(!a)return;const d=new Date();await put('novelties',{...mark(),...x,fechaLocal:d.toLocaleDateString('es-CO'),horaLocal:d.toLocaleTimeString('es-CO')});await put('assets',{...a,ubicacion:x.ubicacion,estado:x.estado,updatedAt:now(),syncState:'pending'});e.target.reset();await refresh();await updateNoveltyOptions()});
$('#conAsset').addEventListener('change',async()=>{const a=(await all('assets')).find(x=>x.id===$('#conAsset').value);$('#conModel').value=a?.modelo||'';if(['28','29'].includes(String(a?.modelo)))$('#origin').value='YT'+a.modelo;await updateParts()});$('#origin').addEventListener('change',updateParts);$('#part').addEventListener('change',async()=>{const p=(await all('parts')).find(x=>x.id===$('#part').value);$('#partNo').value=p?.numero||'';$('#partName').value=p?.nombre||''});
$('#consumptionForm').addEventListener('submit',async e=>{e.preventDefault();const x=fd(e.target),qty=Number(x.cantidad);if(!(qty>0))return alert('Cantidad mínima no válida');const p=(await all('parts')).find(y=>y.id===x.partId);if(!p)return;const d=new Date();await put('consumptions',{...mark(),...x,cantidad:qty,noItem:p.numero||'',nombreRepuesto:p.nombre,fechaLocal:d.toLocaleDateString('es-CO'),horaLocal:d.toLocaleTimeString('es-CO')});e.target.reset();e.target.cantidad.value=1;$('#origin').value='YT29';await refresh()});
$('#syncBtn').addEventListener('click',()=>{$('#syncStatus').textContent='Sincronización con Google Drive appDataFolder: conector pendiente de configurar. Los datos locales están seguros en esta tablet.';alert('La aplicación ya trabaja offline. El siguiente paso es conectar este botón con Google Drive appDataFolder.')});
(async()=>{await openDB();await seedParts();await refresh();await updateNoveltyOptions()})().catch(e=>{console.error(e);alert('No se pudo iniciar el almacenamiento local.')});