// Importación masiva protegida desde Excel para SK Web.
(()=>{
'use strict';
const q=s=>document.querySelector(s);
const clean=v=>(v??'').toString().trim();
const norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'');
const esc=v=>clean(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>{const n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:0};
const date=v=>{
 if(v instanceof Date&&!Number.isNaN(v.valueOf()))return v.toISOString().slice(0,10);
 if(typeof v==='number'&&window.XLSX?.SSF){const d=XLSX.SSF.parse_date_code(v);if(d)return `${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`}
 const s=clean(v);let m=s.match(/^(\d{4})[-/]([01]?\d)[-/]([0-3]?\d)/);if(m)return `${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`;
 m=s.match(/^([0-3]?\d)[-/]([01]?\d)[-/](\d{4})/);return m?`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:s;
};
const ALIASES={
 personal:{id:['id','row id','p_row id'],documento:['documento','cedula','p_no de documento','no de documento'],nombre:['nombre','nombres y apellidos','p_nombres y apellidos'],empresa:['empresa'],area:['area','área'],cargo:['cargo']},
 assets:{id:['id','row id','af_row id'],clase:['clase','af_clase'],numeroYT:['numero de clase','número de clase','numero yt','yt','af_numero yt'],modelo:['modelo','af_modelo'],fabricante:['marca comercial','fabricante','af_fabricante'],marcaInterna:['marca actual','marca interna','af_marca interna'],marcaAnterior:['no de marca actual','marca anterior','af_marca anterior'],nuevaMarca:['nueva marca'],serial:['serial','af_serial'],estadoVisor:['color del visor','estado visor'],largo:['largo','largo ft'],marcada:['marcada fisicamente','marcada físicamente'],mina:['mina propietaria','af_mina propietaria'],fechaIngreso:['fecha de ingreso','af_fecha ingreso'],fechaNovedad:['fecha novedad'],horaNovedad:['hora novedad'],descripcionNovedad:['descripcion de la novedad','descripción de la novedad'],documentoResponsable:['documento responsable'],nombreResponsable:['nombre responsable'],documentoBodeguero:['documento bodeguero','documento bodeguero/a'],nombreBodeguero:['nombre bodeguero','nombre bodeguero/a'],ubicacion:['ubicacion','ubicación','af_ubicacion'],estado:['estado','af_estado'],disponibleEntrega:['disponible entrega'],asignadaId:['asignada a','asignada id'],observaciones:['observaciones']},
 novelties:{id:['id','row id'],assetId:['activo','activo id','asset id'],descripcion:['novedad','descripcion','descripción'],responsableId:['responsable','responsable id'],bodegueroId:['bodeguero','bodeguero id'],ubicacion:['ubicacion','ubicación'],estado:['estado'],observaciones:['observaciones'],fechaLocal:['fecha','fecha local'],horaLocal:['hora','hora local']},
 parts:{id:['id','row id'],clase:['clase'],detalle:['modelo','detalle','inventario'],numero:['numero','número','no de item','item'],nombre:['nombre','nombre del repuesto','repuesto']},
 consumptions:{id:['id','row id'],assetId:['activo id','asset id','activo'],origen:['inventario origen','origen'],partId:['repuesto id','part id'],noItem:['no de item','item'],nombreRepuesto:['nombre del repuesto','repuesto'],cantidad:['cantidad'],responsableId:['responsable id','responsable'],responsableNombre:['nombre responsable'],fechaISO:['fecha iso','fecha'],fechaLocal:['fecha local'],horaLocal:['hora','hora local']},
 incomes:{id:['id','row id'],destino:['inventario destino','destino','inventario'],partId:['repuesto id','part id'],noItem:['no de item','item'],nombreRepuesto:['nombre del repuesto','repuesto'],cantidad:['cantidad'],responsableId:['responsable id','responsable'],responsableNombre:['nombre responsable'],fechaISO:['fecha iso','fecha de ingreso','fecha'],fechaLocal:['fecha local'],horaLocal:['hora','hora local']}
};
const REQUIRED={personal:['documento','nombre'],assets:['clase'],novelties:['assetId','descripcion'],parts:['detalle','nombre'],consumptions:['cantidad','nombreRepuesto'],incomes:['cantidad','nombreRepuesto']};
const LABELS={personal:{documento:'Documento',nombre:'Nombre'},assets:{clase:'Clase',marcaInterna:'Marca actual',serial:'Serial'},novelties:{assetId:'Activo',descripcion:'Novedad'},parts:{detalle:'Inventario',numero:'Item',nombre:'Repuesto'},consumptions:{fechaISO:'Fecha',origen:'Inventario',noItem:'Item',nombreRepuesto:'Repuesto',cantidad:'Cantidad'},incomes:{fechaISO:'Fecha',destino:'Inventario',noItem:'Item',nombreRepuesto:'Repuesto',cantidad:'Cantidad'}};
const ASSET_CLASSES=['YT','Columna','Motosierra','Autorrescatador','Rotomartillo','Pulidora','Taladro','Vibrador de cemento','Pistola de impacto','Sierra circular'];
const ASSET_STANDARD_STATES=['Operativo/a','Averiado/a','En reparación','No apareció','Por dar de baja','Dado/a de baja','Extraviado/a'];
const ASSET_RESCUER_STATES=['Apto según inspección','Pendiente de inspección','No apto – Abierto o activado','No apto – Daño físico visible','No apto – Sello o precinto alterado','No apto – Indicador negro','No apto – Vida útil vencida','En oficina para garantía','Dado de baja'];
const CHOICES={personal:{empresa:['SK 3.7','DESMIN']},parts:{detalle:['28','29']},consumptions:{origen:['YT28','YT29']},incomes:{destino:['YT28','YT29']},assets:{clase:ASSET_CLASSES,estadoVisor:['Marrón','Azul celeste','Blanco','Negro'],marcada:['Sí','No','Desconocido'],mina:['Sandra K','Providencia','El Silencio','Carla','Alianza'],ubicacion:['Bodega de Superficie','Bodega de Producción-N. 4','Socavón'],disponibleEntrega:['Sí','No']}};
let workbook=null,review=null;
function mapHeaders(store,row){const lookup=new Map(Object.keys(row).map(h=>[norm(h),h])),mapped={};for(const[key,names]of Object.entries(ALIASES[store])){const source=names.map(norm).map(x=>lookup.get(x)).find(Boolean);if(source!==undefined)mapped[key]=row[source]}return mapped}
function validateChoices(store,x){const rules={...(CHOICES[store]||{})};if(store==='assets'){rules.modelo=x.clase==='YT'?['28','29']:x.clase==='Autorrescatador'?['Oxypro 50']:[];rules.fabricante=x.clase==='YT'?['Gisi','Irreconocible']:x.clase==='Autorrescatador'?['Steel pro']:[];rules.estado=x.clase==='Autorrescatador'?ASSET_RESCUER_STATES:ASSET_STANDARD_STATES}for(const[field,allowed]of Object.entries(rules)){if(x[field]!==undefined&&x[field]!==''&&!allowed.includes(x[field]))return{field:LABELS[store]?.[field]||field,value:x[field]}}return null}
function prepare(store,raw){const x=mapHeaders(store,raw);for(const k of Object.keys(x))x[k]=clean(x[k]);if(x.fechaISO)x.fechaISO=date(raw[Object.keys(raw).find(h=>ALIASES[store].fechaISO?.map(norm).includes(norm(h))) ]??x.fechaISO);if(x.fechaIngreso)x.fechaIngreso=date(x.fechaIngreso);if(x.fechaNovedad)x.fechaNovedad=date(x.fechaNovedad);if(['consumptions','incomes'].includes(store))x.cantidad=number(x.cantidad);return{data:x,mismatch:validateChoices(store,x)}}
function identity(store,x){if(store==='personal'&&x.documento)return `doc:${norm(x.documento)}`;if(store==='assets')return x.marcaInterna?`marca:${norm(x.marcaInterna)}`:(x.serial?`serial:${norm(x.clase)}:${norm(x.serial)}`:(x.id?`id:${norm(x.id)}`:''));if(store==='parts')return `part:${norm(x.detalle)}:${norm(x.numero)}:${norm(x.nombre)}`;if(store==='consumptions')return `consumo:${norm(x.fechaISO||x.fechaLocal)}:${norm(x.horaLocal)}:${norm(x.assetId)}:${norm(x.origen)}:${norm(x.partId||x.nombreRepuesto)}:${number(x.cantidad)}`;if(store==='incomes')return `ingreso:${norm(x.fechaISO||x.fechaLocal)}:${norm(x.horaLocal)}:${norm(x.destino)}:${norm(x.partId||x.nombreRepuesto)}:${number(x.cantidad)}`;if(store==='novelties')return `novedad:${norm(x.fechaLocal)}:${norm(x.horaLocal)}:${norm(x.assetId)}:${norm(x.descripcion)}`;return x.id?`id:${norm(x.id)}`:''}
function rowName(store,x){const fields=LABELS[store]||{};return Object.keys(fields).map(k=>x[k]).filter(v=>v!==''&&v!=null).slice(0,4).join(' · ')||'Fila sin datos reconocidos'}
function errors(store,x){const e=[];for(const k of REQUIRED[store]||[])if(x[k]===''||x[k]==null||(['consumptions','incomes'].includes(store)&&k==='cantidad'&&!(x[k]>0)))e.push(`Falta ${LABELS[store]?.[k]||k}`);return e}
async function analyze(){
 const store=q('#importStore').value,sheet=q('#importSheet').value;if(!store||!workbook||!sheet)return;
 const raw=XLSX.utils.sheet_to_json(workbook.Sheets[sheet],{defval:'',raw:true}),existing=await all(store),keys=new Set(existing.map(x=>identity(store,x)).filter(Boolean)),seen=new Set;
 const rows=raw.map((source,i)=>{const prepared=prepare(store,source),data=prepared.data,err=errors(store,data),key=identity(store,data);let status='valid';if(!Object.values(data).some(v=>v!==''&&v!=null))status='empty';else if(prepared.mismatch||err.length)status='error';else if(key&&(keys.has(key)||seen.has(key)))status='duplicate';if(key)seen.add(key);return{line:i+2,data,key,status,error:err.join(', '),mismatch:prepared.mismatch,label:rowName(store,data)}}).filter(x=>x.status!=='empty');
 review={store,rows};renderReview();
}
function renderReview(){const rows=review.rows,valid=rows.filter(x=>x.status==='valid').length,dup=rows.filter(x=>x.status==='duplicate').length,bad=rows.filter(x=>x.status==='error').length,first=rows.find(x=>x.mismatch);q('#importResult').hidden=false;q('#importSummary').innerHTML=`${first?`<div class="importMismatch"><b>Texto no coincidente. Corrige e intenta nuevamente.</b><span>Fila ${first.line} · ${esc(first.mismatch.field)}: “${esc(first.mismatch.value)}”</span></div>`:''}<article><b>${rows.length}</b><span>Filas leídas</span></article><article class="ok"><b>${valid}</b><span>Listas para importar</span></article><article class="warn"><b>${dup}</b><span>Duplicadas</span></article><article class="bad"><b>${bad}</b><span>Filas rechazadas</span></article>`;q('#importHead').innerHTML='<tr><th>Fila</th><th>Resultado</th><th>Datos reconocidos</th><th>Detalle</th></tr>';q('#importRows').innerHTML=rows.slice(0,500).map(x=>{const detail=x===first?`Texto no coincidente en ${x.mismatch.field}: “${x.mismatch.value}”. Se rechazó la fila completa.`:x.mismatch?'Pendiente de revisión después de corregir la primera falla.':[x.error,x.status==='duplicate'?'Ya existe en la app o está repetida en el archivo':''].filter(Boolean).join(' · ')||'Se agregará';return`<tr class="import-${x.status}${x===first?' import-first-error':''}"><td>${x.line}</td><td><b>${x.status==='valid'?'Lista':x.status==='duplicate'?'Duplicada':'Rechazada'}</b></td><td>${esc(x.label)}</td><td>${esc(detail)}</td></tr>`}).join('');q('#importConfirm').disabled=!!first||!valid;q('#importConfirm').textContent=first?'Corrige el texto para continuar':`Importar ${valid} fila${valid===1?'':'s'} válida${valid===1?'':'s'}`}
async function readFile(file){if(!window.XLSX)throw new Error('No se pudo cargar el lector de Excel. Conéctate a Internet, actualiza la app y vuelve a intentarlo.');workbook=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});q('#importSheet').innerHTML=workbook.SheetNames.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('');q('#importSheetLabel').hidden=workbook.SheetNames.length<2;await analyze()}
async function confirmImport(){const ready=review?.rows.filter(x=>x.status==='valid')||[];if(!ready.length)return;const btn=q('#importConfirm');btn.disabled=true;btn.textContent='Importando…';try{for(const row of ready){const stamp=new Date().toISOString(),x={...row.data};x.id=x.id||crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;x.createdAt=x.createdAt||stamp;x.updatedAt=stamp;x.syncState='pending';await put(review.store,x)}await refresh();alert(`${ready.length} registro${ready.length===1?'':'s'} importado${ready.length===1?'':'s'} correctamente. Pulsa Sincronizar datos para enviarlos a la base central.`);reset()}catch(e){console.error(e);alert('La importación se detuvo: '+(e?.message||e));btn.disabled=false}}
function reset(){workbook=null;review=null;q('#importForm').reset();q('#pasteForm')?.reset();q('#importSheetLabel').hidden=true;q('#importResult').hidden=true;q('#importRows').innerHTML=''}
function mountPaste(){const upload=q('#importForm');upload.insertAdjacentHTML('beforebegin',`<div class="importTabs"><button type="button" class="active" data-import-mode="file">SUBIR ARCHIVO</button><button type="button" data-import-mode="paste">PEGAR DESDE EXCEL</button></div><form id="pasteForm" class="pasteForm" hidden><label>TABLA DE DESTINO<select id="pasteStore" required>${q('#importStore').innerHTML}</select></label><label class="pasteArea">DATOS COPIADOS DE EXCEL<textarea id="pasteData" rows="12" placeholder="Copia en Excel las columnas con sus encabezados y pégalas aquí" required></textarea></label><p class="pasteRule">Las opciones deben coincidir exactamente con el formulario, incluyendo mayúsculas y tildes. Cualquier valor diferente se descartará.</p><button type="submit">REVISAR DATOS PEGADOS</button></form>`)}
async function readPaste(){const text=q('#pasteData').value.trim();if(!text)return alert('Copia las celdas de Excel y pégalas en el recuadro.');if(!q('#pasteStore').value)return alert('Selecciona la tabla de destino.');if(!window.XLSX)return alert('El lector de Excel todavía no está disponible. Actualiza la app e inténtalo de nuevo.');workbook=XLSX.read(text,{type:'string',raw:true});q('#importStore').value=q('#pasteStore').value;q('#importSheet').innerHTML=workbook.SheetNames.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('');await analyze()}
function bind(){mountPaste();q('#importFile').addEventListener('change',async e=>{try{if(e.target.files[0])await readFile(e.target.files[0])}catch(err){console.error(err);alert(err.message||err)}});q('#importSheet').addEventListener('change',analyze);q('#importStore').addEventListener('change',()=>{if(workbook&&!q('#pasteForm').hidden)q('#pasteStore').value=q('#importStore').value;if(workbook)analyze()});q('#importForm').addEventListener('submit',e=>{e.preventDefault();analyze().catch(console.error)});q('#pasteForm').addEventListener('submit',e=>{e.preventDefault();readPaste().catch(err=>{console.error(err);alert(err.message||err)})});document.querySelectorAll('[data-import-mode]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-import-mode]').forEach(x=>x.classList.toggle('active',x===b));q('#importForm').hidden=b.dataset.importMode!=='file';q('#pasteForm').hidden=b.dataset.importMode!=='paste';q('#importResult').hidden=true;workbook=null;review=null}));q('#importConfirm').addEventListener('click',confirmImport);q('#importCancel').addEventListener('click',reset)}
window.addEventListener('load',()=>{if(q('#bulkImport'))bind()});
})();
