// Importación masiva protegida desde Excel para SK Web.
(()=>{
'use strict';
const q=s=>document.querySelector(s),clean=v=>(v??'').toString().trim(),norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,''),esc=v=>clean(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>{const n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:0};
const ALIASES={
personal:{documento:['documento','cedula','no de documento','p_no de documento'],nombre:['nombre','nombres y apellidos'],empresa:['empresa'],area:['area','área'],cargo:['cargo']},
assets:{clase:['clase'],numeroYT:['numero de clase','número de clase','numero yt'],modelo:['modelo'],fabricante:['marca comercial','fabricante'],marcaInterna:['marca actual','marca interna'],marcaAnterior:['no de marca actual','número de marca actual','numero de marca actual'],nuevaMarca:['nueva marca'],serial:['serial'],estadoVisor:['color del visor'],largo:['largo ft','largo'],marcada:['marcada fisicamente','marcada físicamente'],mina:['mina propietaria'],fechaIngreso:['fecha de ingreso'],ubicacion:['ubicacion','ubicación'],estado:['estado'],disponibleEntrega:['disponible entrega'],observaciones:['observaciones']},
novelties:{assetId:['activo','activo id'],descripcion:['novedad','descripcion','descripción'],responsableId:['responsable','responsable id'],bodegueroId:['bodeguero','bodeguero id'],ubicacion:['ubicacion','ubicación'],estado:['estado'],observaciones:['observaciones']},
parts:{detalle:['modelo','detalle','inventario'],numero:['numero','número','no de item','item'],nombre:['nombre','nombre del repuesto','repuesto']},
consumptions:{assetId:['activo id','activo'],origen:['inventario origen','origen'],partId:['repuesto id'],noItem:['no de item','item'],nombreRepuesto:['nombre del repuesto','repuesto'],cantidad:['cantidad'],responsableId:['responsable id'],responsableNombre:['nombre responsable'],fechaISO:['fecha'],horaLocal:['hora']},
incomes:{destino:['inventario destino','destino','inventario'],partId:['repuesto id'],noItem:['no de item','item'],nombreRepuesto:['nombre del repuesto','repuesto'],cantidad:['cantidad'],responsableId:['responsable id'],responsableNombre:['nombre responsable'],fechaISO:['fecha de ingreso','fecha'],horaLocal:['hora']}
};
const HEADERS={personal:['DOCUMENTO','NOMBRES Y APELLIDOS','EMPRESA','ÁREA','CARGO'],assets:['CLASE','NÚMERO DE CLASE','MODELO','MARCA COMERCIAL','MARCA ACTUAL','No. DE MARCA ACTUAL','NUEVA MARCA','SERIAL','LARGO FT','¿MARCADA FÍSICAMENTE?','MINA PROPIETARIA','FECHA DE INGRESO','UBICACIÓN','ESTADO','DISPONIBLE ENTREGA','OBSERVACIONES'],novelties:['ACTIVO','NOVEDAD','RESPONSABLE','BODEGUERO','UBICACIÓN','ESTADO','OBSERVACIONES'],parts:['INVENTARIO','No. DE ITEM','NOMBRE DEL REPUESTO'],consumptions:['FECHA','HORA','ACTIVO','INVENTARIO ORIGEN','No. DE ITEM','NOMBRE DEL REPUESTO','CANTIDAD','NOMBRE RESPONSABLE'],incomes:['FECHA DE INGRESO','HORA','INVENTARIO DESTINO','No. DE ITEM','NOMBRE DEL REPUESTO','CANTIDAD','NOMBRE RESPONSABLE']};
const CLASSES=['YT','Columna','Motosierra','Autorrescatador','Rotomartillo','Pulidora','Taladro','Vibrador de cemento','Pistola de impacto','Sierra circular'];
const STANDARD=['Operativo/a','Averiado/a','En reparación','No apareció','Por dar de baja','Dado/a de baja','Extraviado/a'];
const RESCUER=['Apto según inspección','Pendiente de inspección','No apto – Abierto o activado','No apto – Daño físico visible','No apto – Sello o precinto alterado','No apto – Indicador negro','No apto – Vida útil vencida','En oficina para garantía','Dado de baja'];
let workbook=null,review=null;
function map(store,row){const lookup=new Map(Object.keys(row).map(h=>[norm(h),h])),x={};for(const[k,names]of Object.entries(ALIASES[store]||{})){const h=names.map(norm).map(n=>lookup.get(n)).find(Boolean);if(h!==undefined)x[k]=clean(row[h])}if(['consumptions','incomes'].includes(store)&&x.cantidad!==undefined)x.cantidad=num(x.cantidad);return x}
function mismatch(store,x){if(store==='personal'&&x.empresa&&!['SK 3.7','DESMIN'].includes(x.empresa))return['EMPRESA',x.empresa];if(store==='assets'){if(x.clase&&!CLASSES.includes(x.clase))return['CLASE',x.clase];const resc=x.clase==='Autorrescatador';if(x.modelo&&!(x.clase==='YT'?['28','29']:resc?['Oxypro 50']:[]).includes(x.modelo))return['MODELO',x.modelo];if(x.fabricante&&!(x.clase==='YT'?['Gisi','Irreconocible']:resc?['Steel pro']:[]).includes(x.fabricante))return['MARCA COMERCIAL',x.fabricante];if(x.estado&&!(resc?RESCUER:STANDARD).includes(x.estado))return['ESTADO',x.estado];if(x.ubicacion&&!['Bodega de Superficie','Bodega de Producción-N. 4','Socavón'].includes(x.ubicacion))return['UBICACIÓN',x.ubicacion]}return null}
function required(store,x){if(store==='personal'&&(!x.documento||!x.nombre))return'Falta DOCUMENTO o NOMBRES Y APELLIDOS';if(store==='assets'){if(!x.clase)return'Falta CLASE';if(!x.numeroYT)return'Falta NÚMERO DE CLASE';if(['YT','Columna'].includes(x.clase)&&!x.marcaInterna)return'Falta MARCA ACTUAL'}if(['consumptions','incomes'].includes(store)&&!(x.cantidad>0))return'CANTIDAD debe ser mayor que cero';return''}
function assetDup(existing,accepted,x){const cls=norm(x.clase),same=[...existing,...accepted].filter(a=>!a.deleted&&norm(a.clase)===cls);const mark=clean(x.marcaInterna||x.marcaActual),serial=clean(x.serial);if(mark&&norm(mark)!=='noaplica'){const f=same.find(a=>norm(a.marcaActual||a.marcaInterna)===norm(mark));if(f)return`MARCA ACTUAL ${mark} ya existe en la clase ${x.clase}${f.numeroYT||f.numeroClase?` (${x.clase} ${f.numeroClase||f.numeroYT})`:''}.`}if(cls!=='columna'&&serial&&norm(serial)!=='noaplica'){const f=same.find(a=>norm(a.serial)===norm(serial));if(f)return`SERIAL ${serial} ya existe en la clase ${x.clase}${f.numeroYT||f.numeroClase?` (${x.clase} ${f.numeroClase||f.numeroYT})`:''}.`}return''}
function genericKey(store,x){if(store==='personal')return x.documento?`d:${norm(x.documento)}`:'';if(store==='parts')return`p:${norm(x.detalle)}:${norm(x.numero)}:${norm(x.nombre)}`;return''}
async function analyze(){const store=q('#importStore').value,sheet=q('#importSheet').value;if(!store||!workbook||!sheet)return;const raw=XLSX.utils.sheet_to_json(workbook.Sheets[sheet],{defval:'',raw:false}),existing=(await all(store)).filter(x=>!x.deleted),accepted=[],keys=new Set(existing.map(x=>genericKey(store,x)).filter(Boolean)),seen=new Set;const rows=[];raw.forEach((source,i)=>{const data=map(store,source);if(!Object.values(data).some(Boolean))return;const mm=mismatch(store,data),req=required(store,data);let duplicate='';const key=genericKey(store,data);if(store==='assets')duplicate=assetDup(existing,accepted,data);else if(key&&(keys.has(key)||seen.has(key)))duplicate='El registro ya existe en la app o está repetido en los datos pegados.';let status=mm||req?'error':duplicate?'duplicate':'valid';if(status==='valid')accepted.push(data);if(key)seen.add(key);rows.push({line:i+2,data,status,mismatch:mm,error:req,duplicate})});review={store,rows};render()}
function render(){const rows=review.rows,first=rows.find(r=>r.mismatch),valid=rows.filter(r=>r.status==='valid').length,dup=rows.filter(r=>r.status==='duplicate').length,bad=rows.filter(r=>r.status==='error').length;q('#importResult').hidden=false;q('#importSummary').innerHTML=`${first?`<div class="importMismatch"><b>Texto no coincidente. Corrige e intenta nuevamente.</b><span>Fila ${first.line} · ${esc(first.mismatch[0])}: “${esc(first.mismatch[1])}”</span></div>`:''}<article><b>${rows.length}</b><span>Filas leídas</span></article><article class="ok"><b>${valid}</b><span>Listas para importar</span></article><article class="warn"><b>${dup}</b><span>Duplicadas</span></article><article class="bad"><b>${bad}</b><span>Filas rechazadas</span></article>`;q('#importHead').innerHTML='<tr><th>FILA</th><th>RESULTADO</th><th>DATOS RECONOCIDOS</th><th>DETALLE</th></tr>';q('#importRows').innerHTML=rows.map(r=>`<tr class="import-${r.status}"><td>${r.line}</td><td><b>${r.status==='valid'?'LISTA':r.status==='duplicate'?'DUPLICADA':'RECHAZADA'}</b></td><td>${esc(Object.values(r.data).filter(Boolean).slice(0,5).join(' · '))}</td><td>${esc(r.mismatch?`Texto no coincidente en ${r.mismatch[0]}: ${r.mismatch[1]}. Se rechazó la fila completa.`:r.error||r.duplicate||'Se agregará.')}</td></tr>`).join('');q('#importConfirm').disabled=!!first||!valid;q('#importConfirm').textContent=first?'CORRIGE EL TEXTO PARA CONTINUAR':`IMPORTAR ${valid} FILA${valid===1?'':'S'} VÁLIDA${valid===1?'':'S'}`}
async function confirmImport(){const ready=review?.rows.filter(r=>r.status==='valid')||[];if(!ready.length)return;for(const r of ready){const stamp=new Date().toISOString(),x={...r.data,id:crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,createdAt:stamp,updatedAt:stamp,syncState:'pending'};if(review.store==='assets'){x.numeroClase=x.numeroYT||'';x.marcaActual=x.marcaInterna||'';x.numeroMarcaActual=x.marcaAnterior||''}await put(review.store,x)}await refresh();alert(`${ready.length} registro${ready.length===1?'':'s'} importado${ready.length===1?'':'s'} correctamente.`);reset()}
function reset(){workbook=null;review=null;q('#importForm')?.reset();q('#pasteForm')?.reset();if(q('#importResult'))q('#importResult').hidden=true}
async function guide(store){let host=q('#importGuide');if(!host){host=document.createElement('div');host.id='importGuide';q('#pasteForm')?.insertAdjacentElement('beforebegin',host)}const rows=(await all(store)).filter(x=>!x.deleted),a=rows[0];const heads=HEADERS[store]||[];if(!heads.length){host.innerHTML='';return}const vals=a?map(store,Object.fromEntries(heads.map(h=>[h,h]))):{};const source=a||{};const aliasValues=heads.map(h=>{const entry=Object.entries(ALIASES[store]||{}).find(([,names])=>names.map(norm).includes(norm(h)));return entry?clean(source[entry[0]]):''});host.innerHTML=`<p class="pasteRule"><b>GUÍA — REGISTRO EXISTENTE, NO EDITABLE Y NO SE IMPORTA</b></p><div class="tableWrap"><table><thead><tr>${heads.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody><tr>${aliasValues.map(v=>`<td>${esc(v||'—')}</td>`).join('')}</tr></tbody></table></div>`}
function setMode(mode){document.querySelectorAll('[data-import-mode]').forEach(b=>b.classList.toggle('active',b.dataset.importMode===mode));q('#importForm').hidden=mode==='paste';q('#pasteForm').hidden=mode!=='paste'}
async function open(store){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='importData'));q('#importStore').value=store;q('#pasteStore').value=store;setMode('paste');await guide(store);q('#pasteData')?.focus();window.scrollTo({top:0,behavior:'instant'})}
function mount(){if(q('#pasteForm'))return;q('#importForm').insertAdjacentHTML('beforebegin',`<div class="importTabs"><button type="button" data-import-mode="file">SUBIR ARCHIVO</button><button type="button" class="active" data-import-mode="paste">PEGAR DESDE EXCEL</button></div><form id="pasteForm" class="pasteForm"><label>TABLA DE DESTINO<select id="pasteStore">${q('#importStore').innerHTML}</select></label><label class="pasteArea">DATOS COPIADOS DE EXCEL<textarea id="pasteData" rows="12" placeholder="Copia en Excel las columnas con sus encabezados y pégalas aquí"></textarea></label><p class="pasteRule">Las opciones deben coincidir exactamente con el formulario. Si una fila contiene un dato no válido, se rechaza la fila completa.</p><button type="submit">REVISAR DATOS PEGADOS</button></form>`);q('#importForm').hidden=true}
function bind(){mount();document.querySelector('.importTabs').addEventListener('click',e=>{const b=e.target.closest('[data-import-mode]');if(b)setMode(b.dataset.importMode)});q('#pasteStore').addEventListener('change',()=>{q('#importStore').value=q('#pasteStore').value;guide(q('#pasteStore').value)});q('#pasteForm').addEventListener('submit',async e=>{e.preventDefault();const text=q('#pasteData').value.trim();if(!text)return alert('Copia las celdas de Excel y pégalas en el recuadro.');workbook=XLSX.read(text,{type:'string',raw:true});q('#importStore').value=q('#pasteStore').value;q('#importSheet').innerHTML=workbook.SheetNames.map(n=>`<option>${esc(n)}</option>`).join('');await analyze()});q('#importFile').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;workbook=XLSX.read(await f.arrayBuffer(),{type:'array',cellDates:true});q('#importSheet').innerHTML=workbook.SheetNames.map(n=>`<option>${esc(n)}</option>`).join('');q('#importSheetLabel').hidden=workbook.SheetNames.length<2;await analyze()});q('#importForm').addEventListener('submit',e=>{e.preventDefault();analyze()});q('#importSheet').addEventListener('change',analyze);q('#importConfirm').addEventListener('click',confirmImport);q('#importCancel').addEventListener('click',reset);window.SKBulkImport={open}}
window.addEventListener('load',()=>{if(q('#bulkImport'))bind()});
})();