// Administración de accesos de Plaza Blending desde SK Admin.
(()=>{
  'use strict';
  const el=s=>document.querySelector(s);let selected=null,lastInvite='';
  const wording=value=>String(value||'').replace(/Documento y PIN/gi,'Documento y contraseña').replace(/PIN incorrecto/gi,'Contraseña incorrecta').replace(/un PIN/gi,'una contraseña');
  const clean=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const people=async()=>(await all('personal')).filter(x=>!x.deleted);
  function accessLabel(x){if(x.plazaEnabled)return'ACCESO ACTIVO';if(x.plazaAccessState==='pending')return'INVITACIÓN PENDIENTE';return'SIN ACCESO'}
  async function render(){const q=(el('#plazaUserSearch')?.value||'').trim().toLowerCase(),rows=(await people()).filter(x=>!q||[x.nombre,x.documento,x.cargo,x.area].join(' ').toLowerCase().includes(q));el('#plazaUserCount').textContent=`${rows.length} colaboradores`;el('#plazaUserList').innerHTML=rows.sort((a,b)=>(a.nombre||'').localeCompare(b.nombre||'','es')).map(x=>`<button type="button" class="plazaUserRow ${selected?.id===x.id?'active':''}" data-plaza-person="${clean(x.id)}"><span><b>${clean(x.nombre||'Sin nombre')}</b><small>${clean(x.documento||'Sin documento')} · ${clean(x.cargo||'Sin cargo')}</small></span><span class="plazaAccessBadge ${x.plazaEnabled?'enabled':''}">${accessLabel(x)}</span></button>`).join('')||'<p class="hint">No hay colaboradores que coincidan.</p>'}
  function prepareForm(){const f=el('#plazaAccessForm');if(!f)return;const pin=f.elements.pin;if(pin){pin.closest('label').hidden=true;pin.required=false}const submit=el('#plazaEnableBtn');if(submit)submit.textContent='GENERAR ENLACE DE ACCESO';const hint=el('#plazaAccess')?.querySelector('.hint');if(hint)hint.textContent='Selecciona un colaborador y genera un enlace personal de un solo uso. El funcionario crea su propia contraseña y el administrador nunca la ve.';let box=el('#plazaInviteBox');if(!box){box=document.createElement('div');box.id='plazaInviteBox';box.hidden=true;box.innerHTML='<label>ENLACE TEMPORAL<input id="plazaInviteLink" readonly></label><button type="button" id="plazaCopyInvite">COPIAR ENLACE</button><small>Válido por 24 horas y para un solo uso.</small>';el('#plazaAccessState').after(box);el('#plazaCopyInvite').addEventListener('click',async()=>{if(!lastInvite)return;try{await navigator.clipboard.writeText(lastInvite);alert('Enlace copiado. Envíalo únicamente al funcionario habilitado.')}catch(_){el('#plazaInviteLink').select();document.execCommand('copy')}})}}
  function select(person){selected=person;lastInvite='';const f=el('#plazaAccessForm');f.elements.id.value=person.id||'';f.elements.nombre.value=person.nombre||'';f.elements.document.value=person.documento||'';el('#plazaInviteBox').hidden=true;el('#plazaAccessState').textContent=person.plazaEnabled?'Acceso activo. Puedes generar un nuevo enlace si el funcionario necesita cambiar su contraseña.':person.plazaAccessState==='pending'?'Invitación pendiente. Puedes generar una nueva; la anterior quedará anulada.':'Este colaborador no tiene acceso a Plaza Blending.';el('#plazaDisableBtn').disabled=!person.plazaEnabled&&person.plazaAccessState!=='pending';render()}
  async function request(body){const c=window.SK_SYNC_CONFIG||{};if(!c.apiUrl||!c.apiKey)throw new Error('El servicio central no está configurado');const r=await fetch(c.apiUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({...body,action:'plazaUserAdmin',key:c.apiKey}),redirect:'follow'}),text=await r.text();let result;try{result=JSON.parse(text)}catch(_){throw new Error('El servidor no devolvió una respuesta válida')}if(!result.ok)throw new Error(result.error||'No se pudo actualizar el acceso');return result}
  async function generateInvite(){if(!selected)return alert('Selecciona primero un colaborador.');const f=el('#plazaAccessForm');f.querySelectorAll('button').forEach(b=>b.disabled=true);el('#plazaAccessState').textContent='Generando enlace seguro…';try{const setupUrl=new URL('plaza/password.html',location.href).href,result=await request({document:selected.documento,enabled:true,mode:'invite',role:'operator',setupUrl}),current=(await people()).find(x=>x.id===selected.id),updated={...current,plazaAccessState:'pending',updatedAt:new Date().toISOString()};await put('personal',updated);selected=updated;lastInvite=result.inviteUrl;el('#plazaInviteLink').value=lastInvite;el('#plazaInviteBox').hidden=false;el('#plazaAccessState').textContent='Enlace generado. La contraseña será creada únicamente por el funcionario.';await render()}catch(e){el('#plazaAccessState').textContent='No se pudo generar: '+wording(e?.message||e);alert(wording(e?.message||e))}finally{el('#plazaEnableBtn').disabled=false;el('#plazaDisableBtn').disabled=!selected?.plazaEnabled&&selected?.plazaAccessState!=='pending'}}
  async function disable(){if(!selected)return alert('Selecciona primero un colaborador.');if(!confirm(`¿Quitar el acceso a Plaza Blending de ${selected.nombre}?`))return;try{const result=await request({document:selected.documento,enabled:false}),current=(await people()).find(x=>x.id===selected.id),updated={...current,plazaEnabled:false,plazaAccessState:'none',updatedAt:new Date().toISOString()};await put('personal',updated);select(updated);alert('Acceso de Plaza Blending desactivado.')}catch(e){alert(wording(e?.message||e))}}
  window.addEventListener('load',()=>{prepareForm();el('.plazaAccessBtn')?.addEventListener('click',()=>{showView('plazaAccess');render()});el('[data-return-home]')?.addEventListener('click',()=>showView('home'));el('#plazaUserSearch')?.addEventListener('input',render);el('#plazaUserList')?.addEventListener('click',async e=>{const b=e.target.closest('[data-plaza-person]');if(!b)return;const person=(await people()).find(x=>x.id===b.dataset.plazaPerson);if(person)select(person)});el('#plazaAccessForm')?.addEventListener('submit',e=>{e.preventDefault();generateInvite()});el('#plazaDisableBtn')?.addEventListener('click',disable)});
})();
