// Administración de accesos de Plaza Blending desde SK Admin.
(()=>{
  'use strict';
  const el=s=>document.querySelector(s);let selected=null;
  const wording=value=>String(value||'').replace(/Documento y PIN/gi,'Documento y contraseña').replace(/PIN incorrecto/gi,'Contraseña incorrecta').replace(/un PIN/gi,'una contraseña');
  const clean=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const people=async()=>(await all('personal')).filter(x=>!x.deleted);
  async function render(){const q=(el('#plazaUserSearch')?.value||'').trim().toLowerCase(),rows=(await people()).filter(x=>!q||[x.nombre,x.documento,x.cargo,x.area].join(' ').toLowerCase().includes(q));el('#plazaUserCount').textContent=`${rows.length} colaboradores`;el('#plazaUserList').innerHTML=rows.sort((a,b)=>(a.nombre||'').localeCompare(b.nombre||'','es')).map(x=>`<button type="button" class="plazaUserRow ${selected?.id===x.id?'active':''}" data-plaza-person="${clean(x.id)}"><span><b>${clean(x.nombre||'Sin nombre')}</b><small>${clean(x.documento||'Sin documento')} · ${clean(x.cargo||'Sin cargo')}</small></span><span class="plazaAccessBadge ${x.plazaEnabled?'enabled':''}">${x.plazaEnabled?'Bodeguero/a':'Sin acceso'}</span></button>`).join('')||'<p class="hint">No hay colaboradores que coincidan.</p>'}
  function select(person){selected=person;const f=el('#plazaAccessForm');f.elements.id.value=person.id||'';f.elements.nombre.value=person.nombre||'';f.elements.document.value=person.documento||'';f.elements.pin.value='';el('#plazaAccessState').textContent=person.plazaEnabled?'Acceso activo como Bodeguero/a.':'Este colaborador no tiene acceso a Plaza Blending.';el('#plazaDisableBtn').disabled=!person.plazaEnabled;render()}
  async function request(body){const c=window.SK_SYNC_CONFIG||{};if(!c.apiUrl||!c.apiKey)throw new Error('El servicio central no está configurado');const r=await fetch(c.apiUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({...body,action:'plazaUserAdmin',key:c.apiKey,token:window.SKAdminAuth?.token?.()||''}),redirect:'follow'}),text=await r.text();let result;try{result=JSON.parse(text)}catch(_){throw new Error('El servidor no devolvió una respuesta válida')}if(!result.ok)throw new Error(result.error||'No se pudo actualizar el acceso');return result.user}
  async function save(enabled){if(!selected)return alert('Selecciona primero un colaborador.');const f=el('#plazaAccessForm'),pin=f.elements.pin.value.trim(),role='operator';if(enabled&&!selected.plazaEnabled&&!pin)return alert('Escribe una contraseña para habilitar el acceso.');if(pin&&pin.length<4)return alert('La contraseña debe tener al menos 4 caracteres.');if(!enabled&&!confirm(`¿Quitar el acceso a Plaza Blending de ${selected.nombre}?`))return;f.querySelectorAll('button').forEach(b=>b.disabled=true);el('#plazaAccessState').textContent='Guardando acceso…';try{const result=await request({document:selected.documento,pin,role,enabled}),current=(await people()).find(x=>x.id===selected.id),updated={...current,plazaEnabled:result.plazaEnabled,plazaRole:result.plazaRole||'',updatedAt:new Date().toISOString()};await put('personal',updated);select(updated);alert(enabled?'Acceso de Plaza Blending guardado.':'Acceso de Plaza Blending desactivado.')}catch(e){el('#plazaAccessState').textContent='No se pudo guardar: '+wording(e?.message||e);alert(wording(e?.message||e))}finally{el('#plazaEnableBtn').disabled=false;el('#plazaDisableBtn').disabled=!selected?.plazaEnabled}}
  window.addEventListener('load',()=>{el('.plazaAccessBtn')?.addEventListener('click',()=>{showView('plazaAccess');render()});document.addEventListener('click',e=>{const home=e.target.closest('#plazaAccess [data-return-home]');if(home){e.preventDefault();selected=null;el('#plazaAccessForm')?.reset();el('#plazaAccessState').textContent='Sin colaborador seleccionado.';showView('home');return}const cancel=e.target.closest('#plazaAccessCancelBtn');if(cancel){e.preventDefault();selected=null;el('#plazaAccessForm')?.reset();el('#plazaAccessState').textContent='Sin colaborador seleccionado.';el('#plazaDisableBtn').disabled=true;render()}});el('#plazaUserSearch')?.addEventListener('input',render);el('#plazaUserList')?.addEventListener('click',async e=>{const b=e.target.closest('[data-plaza-person]');if(!b)return;const person=(await people()).find(x=>x.id===b.dataset.plazaPerson);if(person)select(person)});el('#plazaAccessForm')?.addEventListener('submit',e=>{e.preventDefault();save(true)});el('#plazaDisableBtn')?.addEventListener('click',()=>save(false))});
})();
