// Administración de accesos de Plaza Blending desde SK Admin.
(()=>{
  'use strict';
  const el=s=>document.querySelector(s);let selected=null;
  const wording=value=>String(value||'').replace(/Documento y PIN/gi,'Documento y contraseña').replace(/PIN incorrecto/gi,'Contraseña incorrecta').replace(/un PIN/gi,'una contraseña');
  const clean=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const people=async()=>(await all('personal')).filter(x=>!x.deleted);
  async function render(){const q=(el('#plazaUserSearch')?.value||'').trim().toLowerCase(),rows=(await people()).filter(x=>!q||[x.nombre,x.documento,x.cargo,x.area].join(' ').toLowerCase().includes(q));el('#plazaUserCount').textContent=`${rows.length} colaboradores`;el('#plazaUserList').innerHTML=rows.sort((a,b)=>(a.nombre||'').localeCompare(b.nombre||'','es')).map(x=>`<button type="button" class="plazaUserRow ${selected?.id===x.id?'active':''}" data-plaza-person="${clean(x.id)}"><span><b>${clean(x.nombre||'Sin nombre')}</b><small>${clean(x.documento||'Sin documento')} · ${clean(x.cargo||'Sin cargo')}</small></span><span class="plazaAccessBadge ${x.plazaEnabled?'enabled':''}">${x.plazaEnabled?'Bodeguero/a':'Sin acceso'}</span></button>`).join('')||'<p class="hint">No hay colaboradores que coincidan.</p>'}
  function select(person){selected=person;const f=el('#plazaAccessForm');f.elements.id.value=person.id||'';f.elements.nombre.value=person.nombre||'';f.elements.document.value=person.documento||'';el('#plazaCopyInvite').hidden=true;el('#plazaAccessState').textContent=person.plazaEnabled?'Acceso activo como Bodeguero/a.':'Este colaborador no tiene acceso a Plaza Blending.';el('#plazaDisableBtn').disabled=!person.plazaEnabled;render()}
  let invitationUrl='';
  async function save(enabled){if(!selected)return alert('Selecciona primero un colaborador.');if(!enabled&&!confirm(`¿Quitar el acceso a Plaza Blending de ${selected.nombre}?`))return;const f=el('#plazaAccessForm');f.querySelectorAll('button').forEach(b=>b.disabled=true);el('#plazaAccessState').textContent=enabled?'Generando invitación…':'Desactivando acceso…';try{if(enabled){const result=await window.SKAdminAuth.request('accessInvitationCreate',{scope:'plaza',personId:selected.id});invitationUrl=new URL('crear-acceso.html?invite='+encodeURIComponent(result.token),location.href).href;el('#plazaCopyInvite').hidden=false;el('#plazaAccessState').textContent='Enlace válido por 24 horas. El colaborador creará su propia contraseña.'}else{const result=await window.SKAdminAuth.request('plazaUserAdmin',{document:selected.documento,enabled:false});const current=(await people()).find(x=>x.id===selected.id);const updated={...current,plazaEnabled:false,plazaRole:'',updatedAt:new Date().toISOString()};await put('personal',updated);selected=updated;invitationUrl='';el('#plazaCopyInvite').hidden=true;el('#plazaAccessState').textContent='Acceso desactivado.';render()}}catch(e){el('#plazaAccessState').textContent='No se pudo guardar: '+wording(e?.message||e)}finally{el('#plazaEnableBtn').disabled=false;el('#plazaDisableBtn').disabled=!selected?.plazaEnabled;el('#plazaCopyInvite').disabled=false;el('#plazaAccessCancelBtn').disabled=false}}
  window.addEventListener('load',()=>{el('.plazaAccessBtn')?.addEventListener('click',()=>{if(!window.SKAdminAuth?.isOwner?.())return;showView('plazaAccess');render()});document.addEventListener('click',e=>{const home=e.target.closest('#plazaAccess [data-return-home]');if(home){e.preventDefault();selected=null;invitationUrl='';el('#plazaCopyInvite').hidden=true;el('#plazaAccessForm')?.reset();el('#plazaAccessState').textContent='Sin colaborador seleccionado.';showView('home');return}const cancel=e.target.closest('#plazaAccessCancelBtn');if(cancel){e.preventDefault();selected=null;invitationUrl='';el('#plazaCopyInvite').hidden=true;el('#plazaAccessForm')?.reset();el('#plazaAccessState').textContent='Sin colaborador seleccionado.';el('#plazaDisableBtn').disabled=true;render()}});el('#plazaCopyInvite')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(invitationUrl);el('#plazaAccessState').textContent='Enlace copiado. Envíalo al colaborador.'}catch(_){prompt('Copia el enlace:',invitationUrl)}});el('#plazaUserSearch')?.addEventListener('input',render);el('#plazaUserList')?.addEventListener('click',async e=>{const b=e.target.closest('[data-plaza-person]');if(!b)return;const person=(await people()).find(x=>x.id===b.dataset.plazaPerson);if(person)select(person)});el('#plazaAccessForm')?.addEventListener('submit',e=>{e.preventDefault();save(true)});el('#plazaDisableBtn')?.addEventListener('click',()=>save(false))});
})();

