// Sincronización automática local-first. Una falla de red nunca impide registrar.
(()=>{
  const config=()=>window.SK_SYNC_CONFIG||{};let running=false,timer=0,activePromise=null;
  const configured=()=>/^https:\/\/script\.google\.com\/macros\/s\/.+\/exec(?:\?.*)?$/.test(config().apiUrl||'');
  const ui=state=>window.SKAdminSyncUI?.setState?.(state);
  function buttonStart(){const b=document.querySelector('#updateAppBtn');if(!b||b.dataset.busy==='true')return null;b.disabled=true;b.dataset.autoSync='true';b.classList.add('isSyncing');b.textContent='☁ SINCRONIZANDO';return b}
  function buttonStop(b){if(!b||b.dataset.busy==='true')return;delete b.dataset.autoSync;b.disabled=false;b.classList.remove('isSyncing');b.textContent='☁ SINCRONIZAR'}
  async function pendingSnapshot(){const snapshot={schema:6,updatedAt:new Date().toISOString()};for(const store of stores)snapshot[store]=(await all(store)).filter(row=>row?.syncState==='pending');return snapshot}
  const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
  function isTransient(error){const msg=String(error?.message||error||'').toLowerCase();return error?.name==='AbortError'||msg.includes('load failed')||msg.includes('failed to fetch')||msg.includes('network')||msg.includes('respondió 429')||msg.includes('respondió 5')}
  async function sendOnce(snapshot,attempt){const c=config(),controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),attempt===1?18000:30000);try{const r=await fetch(c.apiUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'sync',key:c.apiKey,since:localStorage.getItem('skWebServerUpdatedAt')||'',data:snapshot}),signal:controller.signal,redirect:'follow',cache:'no-store',credentials:'omit'});if(!r.ok)throw new Error(`El servicio respondió ${r.status}`);let result;try{result=await r.json()}catch(_){throw new Error('El servicio devolvió una respuesta incompleta')}if(!result.ok)throw new Error(result.error||'El servicio rechazó la sincronización');return result}finally{clearTimeout(timeout)}}
  async function send(snapshot){let lastError;for(let attempt=1;attempt<=2;attempt++){try{return await sendOnce(snapshot,attempt)}catch(e){lastError=e;if(!isTransient(e)||attempt===2)break;await wait(1200)}}throw lastError}
  async function performSync({silent=false}={}){const b=buttonStart(),s=document.querySelector('#syncStatus');try{running=true;ui('syncing');if(s)s.textContent='Guardando cambios en la base central…';const snapshot=await pendingSnapshot(),result=await send(snapshot),serverUpdatedAt=result.updatedAt||result.data?.updatedAt||'';if(serverUpdatedAt)localStorage.setItem('skWebServerUpdatedAt',serverUpdatedAt);if(result.notModified){if(s)s.textContent=`Sincronizado · sin cambios · ${new Date().toLocaleString('es-CO')}`;ui('synced');window.dispatchEvent(new CustomEvent('skweb-synced',{detail:{source:'api',notModified:true}}));return true}const merged=result.data;if(!merged||typeof merged!=='object')throw new Error('El servicio no devolvió la base sincronizada');const localAssetIds=new Set((await all('assets')).map(x=>x.id).filter(Boolean)),mergedAssetIds=new Set((merged.assets||[]).map(x=>x.id));for(const [store,rows] of Object.entries(merged))if(Array.isArray(rows))merged[store]=rows.map(row=>row?.syncState==='pending'?{...row,syncState:'synced'}:row);for(const id of localAssetIds)if(!mergedAssetIds.has(id))throw new Error('Protección local: un activo iba a perderse.');if(typeof window.writeSyncedSnapshot!=='function')throw new Error('No se cargó el conciliador local');await window.writeSyncedSnapshot(merged);await seedParts();await refresh();window.SKInventoryAdmin?.render?.();if(s)s.textContent=`Sincronizado automáticamente · ${new Date().toLocaleString('es-CO')}`;ui('synced');window.dispatchEvent(new CustomEvent('skweb-synced',{detail:{source:'api'}}));window.dispatchEvent(new Event('skweb-inventory-refresh'));return true}catch(e){console.error('SK Web automatic sync:',e);ui('error');if(s)s.textContent=navigator.onLine?'Cambios seguros en este dispositivo · sincronización pendiente':'Sin conexión · cambios seguros en este dispositivo';if(!silent)alert('Los datos están seguros en este dispositivo, pero aún no se sincronizaron: '+(e?.message||e));return false}finally{running=false;buttonStop(b)}}
  function sync(options={}){if(!configured()||!navigator.onLine)return Promise.resolve(false);if(activePromise)return activePromise;activePromise=performSync(options).finally(()=>{activePromise=null});return activePromise}
  function schedule(delay=1500){if(!configured())return;clearTimeout(timer);timer=setTimeout(()=>sync({silent:true}),delay)}
  window.skSyncApi={configured,sync,schedule};window.addEventListener('online',()=>schedule(1200));window.addEventListener('offline',()=>ui('error'));window.addEventListener('load',()=>{if(!configured())return;schedule(2500);setInterval(()=>schedule(0),Math.max(60000,Number(config().intervalMs)||300000));document.addEventListener('submit',()=>schedule(3500),true)});
})();
