// Sincronización automática local-first. Una falla de red nunca impide registrar.
(()=>{
  const config=()=>window.SK_SYNC_CONFIG||{};let running=false,timer=0,activePromise=null;
  const configured=()=>/^https:\/\/script\.google\.com\/macros\/s\/.+\/exec(?:\?.*)?$/.test(config().apiUrl||'');
  const ui=state=>window.SKAdminSyncUI?.setState?.(state);
  function buttonStart(){const b=document.querySelector('#updateAppBtn');if(!b||b.dataset.busy==='true')return null;b.disabled=true;b.dataset.autoSync='true';b.classList.add('isSyncing');b.textContent='☁ SINCRONIZANDO';return b}
  function buttonStop(b){if(!b||b.dataset.busy==='true')return;delete b.dataset.autoSync;b.disabled=false;b.classList.remove('isSyncing');b.textContent='☁ SINCRONIZAR'}
  async function send(snapshot){const c=config(),controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),45000);try{const r=await fetch(c.apiUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'sync',key:c.apiKey,data:snapshot}),signal:controller.signal,redirect:'follow'});if(!r.ok)throw new Error(`El servicio respondió ${r.status}`);const result=await r.json();if(!result.ok)throw new Error(result.error||'El servicio rechazó la sincronización');return result.data}finally{clearTimeout(timeout)}}
  async function performSync({silent=false}={}){const b=buttonStart(),s=document.querySelector('#syncStatus');try{running=true;ui('syncing');if(s)s.textContent='Guardando cambios en la base central…';const localAssetIds=new Set((await all('assets')).map(x=>x.id).filter(Boolean)),merged=await send(await localSnapshot()),mergedAssetIds=new Set((merged.assets||[]).map(x=>x.id));for(const id of localAssetIds)if(!mergedAssetIds.has(id))throw new Error('Protección local: un activo iba a perderse.');if(typeof window.writeSyncedSnapshot!=='function')throw new Error('No se cargó el conciliador local');await window.writeSyncedSnapshot(merged);await seedParts();await refresh();if(s)s.textContent=`Sincronizado automáticamente · ${new Date().toLocaleString('es-CO')}`;ui('synced');window.dispatchEvent(new CustomEvent('skweb-synced',{detail:{source:'api'}}));return true}catch(e){console.error('SK Web automatic sync:',e);ui('error');if(s)s.textContent=navigator.onLine?'Cambios seguros en este dispositivo · sincronización pendiente':'Sin conexión · cambios seguros en este dispositivo';if(!silent)alert('Los datos están seguros en este dispositivo, pero aún no se sincronizaron: '+(e?.message||e));return false}finally{running=false;buttonStop(b)}}
  function sync(options={}){if(!configured()||!navigator.onLine)return Promise.resolve(false);if(activePromise)return activePromise;activePromise=performSync(options).finally(()=>{activePromise=null});return activePromise}
  function schedule(delay=1500){if(!configured())return;clearTimeout(timer);timer=setTimeout(()=>sync({silent:true}),delay)}
  window.skSyncApi={configured,sync,schedule};window.addEventListener('online',()=>schedule(300));window.addEventListener('offline',()=>ui('error'));window.addEventListener('load',()=>{if(!configured())return;schedule(800);setInterval(()=>schedule(0),Math.max(15000,Number(config().intervalMs)||60000));document.addEventListener('submit',()=>schedule(2000),true)});
})();
