export type Person={id:string;document:string;name:string;role:string;phone:string;status:string;notes:string};
export type PersonnelEvent={id:string;personId:string;kind:string;start:string;end:string;place:string;notes:string};
export type Data={people:Person[];events:PersonnelEvent[]};
export const roles=['Operador de seguridad','Escolta','Supervisor','Jefe de seguridad'];
export const statuses=['Disponible','Descanso','No disponible','Inactivo'];
const text=(v:unknown,max=500)=>typeof v==='string'?v.trim().slice(0,max):'';
export function validateRecord(type:unknown,input:any):any{if(!input||typeof input!=='object')throw new Error('Registro inválido.');const id=text(input.id,80);if(!/^[a-zA-Z0-9-]{8,80}$/.test(id))throw new Error('Identificador inválido.');if(type==='person'){const document=text(input.document,40),name=text(input.name,150),role=text(input.role,80),status=text(input.status,40);if(!document||!name)throw new Error('Completa documento y nombre.');if(!roles.includes(role)||!statuses.includes(status))throw new Error('Selecciona cargo y disponibilidad válidos.');return{id,document,name,role,status,phone:text(input.phone,40),notes:text(input.notes)}}if(type==='event'){const start=new Date(input.start),end=new Date(input.end),personId=text(input.personId,80),kind=text(input.kind,30);if(!personId||!['Servicio','Permiso'].includes(kind)||!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||end<=start)throw new Error('La finalización debe ser posterior al inicio.');const place=text(input.place,150);if(!place)throw new Error(kind==='Servicio'?'Ingresa el puesto o lugar del servicio.':'Ingresa el motivo del permiso.');return{id,personId,kind,start:start.toISOString(),end:end.toISOString(),place,notes:text(input.notes)}}throw new Error('Tipo de registro inválido.')}
export function personStatus(person:Person,events:PersonnelEvent[],now=Date.now()){if(person.status==='Inactivo')return 'Inactivo';const active=events.find(e=>e.personId===person.id&&Date.parse(e.start)<=now&&Date.parse(e.end)>now);return active?active.kind==='Servicio'?'En servicio':'En permiso':person.status}
export function hours(event:PersonnelEvent){return Math.max(0,(Date.parse(event.end)-Date.parse(event.start))/3600000)}
export function monthHours(personId:string,events:PersonnelEvent[],month:string){const start=Date.parse(month+'-01T00:00:00-05:00'),[y,m]=month.split('-').map(Number),end=Date.parse(`${m===12?y+1:y}-${String(m===12?1:m+1).padStart(2,'0')}-01T00:00:00-05:00`);return events.filter(e=>e.personId===personId&&e.kind==='Servicio').reduce((sum,e)=>sum+Math.max(0,(Math.min(Date.parse(e.end),end,Date.now())-Math.max(Date.parse(e.start),start))/3600000),0)}
export const dateTime=(iso:string)=>new Date(iso).toLocaleString('es-CO',{timeZone:'America/Bogota',day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'});
export const currentMonth=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Bogota',year:'numeric',month:'2-digit'}).format(new Date()).slice(0,7);
