(()=>{'use strict';const $=s=>document.querySelector(s),api=()=>window.SK_SYNC_CONFIG?.apiUrl||'',uuid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;let token=sessionStorage.getItem('skPlazaToken')||'',user=JSON.parse(sessionStorage.getItem('skPlazaUser')||'null'),data={};
async function post(body){if(!api())throw new Error('El servicio central todavía no está configurado.');const r=await fetch(api(),{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body),redirect:'follow'}),x=await r.json();if(!x.ok)throw new Error(x.error||'Solicitud rechazada');return x}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));function options(rows,label){return '<option value="">Seleccionar…</option>'+rows.filter(x=>!x.deleted).map(x=>`<option value="${esc(x.id)}">${esc(label(x))}</option>`).join('')}
function render(){const criteria=data.inventoryCriteria||[],stock=new Map((data.inventoryStock||[]).map(x=>[x.itemId,Number(x.quantity)||0]));document.querySelectorAll('[name=itemId]').forEach(s=>s.innerHTML=options(criteria,x=>`${x.name||x.element||'Elemento'} · Disponibles: ${stock.get(x.id)||0}`));$('#deliveryForm [name=recipientId]').innerHTML=options(data.personal||[],x=>`${x.documento||''} - ${x.nombre||''}`);$('#userName').textContent=user?.nombre||user?.documento||''}
async function sync(silent=false){try{$('#syncStatus').textContent='Sincronizando…';const x=await post({action:'plazaSync',token,data:{blendingIncomes:(data.blendingIncomes||[]).filter(x=>x.syncState==='pending'),blendingDeliveries:(data.blendingDeliveries||[]).filter(x=>x.syncState==='pending')}});data=x.data;localStorage.setItem('skPlazaData',JSON.stringify(data));render();$('#syncStatus').textContent=`Sincronizado · ${new Date().toLocaleString('es-CO')}`}catch(e){$('#syncStatus').textContent='Pendiente de sincronización';if(!silent)alert(e.message);if(/sesión venció|sesión no válida/i.test(e.message))logout()}}
function openApp(){data=JSON.parse(localStorage.getItem('skPlazaData')||'{}');$('#login').hidden=true;$('#app').hidden=false;$('#syncBtn').hidden=false;render();sync(true)}function logout(){sessionStorage.removeItem('skPlazaToken');sessionStorage.removeItem('skPlazaUser');location.reload()}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{$('#loginStatus').textContent='Verificando…';const x=await post({action:'plazaLogin',document:f.get('document'),pin:f.get('pin')});token=x.token;user=x.user;sessionStorage.setItem('skPlazaToken',token);sessionStorage.setItem('skPlazaUser',JSON.stringify(user));openApp()}catch(err){$('#loginStatus').textContent=err.message}});
function movement(form,store){const f=Object.fromEntries(new FormData(form)),quantity=Number(f.quantity);if(!(quantity>0))return alert('Cantidad mínima no válida');const item=(data.inventoryCriteria||[]).find(x=>x.id===f.itemId);if(!item)return alert('Selecciona el elemento.');if(store==='blendingDeliveries'){const balance=new Map((data.inventoryStock||[]).map(x=>[x.itemId,Number(x.quantity)||0]));if(quantity>(balance.get(f.itemId)||0))return alert('La cantidad ingresada supera la disponibilidad')}const row={id:uuid(),...f,quantity,itemName:item.name||item.element||'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),syncState:'pending'};(data[store]||(data[store]=[])).push(row);localStorage.setItem('skPlazaData',JSON.stringify(data));form.reset();sync(false)}
$('#incomeForm').addEventListener('submit',e=>{e.preventDefault();movement(e.currentTarget,'blendingIncomes')});$('#deliveryForm').addEventListener('submit',e=>{e.preventDefault();movement(e.currentTarget,'blendingDeliveries')});$('nav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===b.dataset.view))});$('#syncBtn').addEventListener('click',()=>sync(false));$('#logoutBtn').addEventListener('click',logout);if(token&&user)openApp();
})();
