(()=>{
  'use strict';
  const $=selector=>document.querySelector(selector),api=()=>window.SK_SYNC_CONFIG?.apiUrl||'',uuid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
  let token=sessionStorage.getItem('skPlazaToken')||'',user=JSON.parse(sessionStorage.getItem('skPlazaUser')||'null'),data={};
  async function post(body){if(!api())throw new Error('El servicio central todavía no está configurado.');const response=await fetch(api(),{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body),redirect:'follow'}),result=await response.json();if(!result.ok)throw new Error(result.error||'Solicitud rechazada');return result}
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const norm=value=>String(value||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
  const itemName=item=>String(item?.name||item?.element||'').trim();
  const assetNumber=asset=>String(asset.numeroClase||asset.numeroYT||asset.orden||'').trim();
  function options(rows,label){return '<option value="">Seleccionar…</option>'+rows.filter(row=>!row.deleted).map(row=>`<option value="${esc(row.id)}">${esc(label(row))}</option>`).join('')}
  function isRetired(asset){return /dado\/?a? de baja|retirado|desechado/i.test(`${asset.estado||''} ${asset.ubicacion||''}`)}
  function isFixedItem(item){const name=norm(itemName(item));return Boolean(item?.isFixedAsset===true||item?.esActivoFijo===true||item?.fixedAsset===true||(data.assets||[]).some(asset=>!asset.deleted&&norm(asset.clase)===name))}
  function deliveryItems(){const criteria=(data.inventoryCriteria||[]).filter(item=>!item.deleted),known=new Set(criteria.map(item=>norm(itemName(item)))),classes=new Map();(data.assets||[]).filter(asset=>!asset.deleted&&!isRetired(asset)&&asset.clase).forEach(asset=>{const key=norm(asset.clase);if(!known.has(key)&&!classes.has(key))classes.set(key,{id:`asset-class:${key}`,name:asset.clase,isFixedAsset:true})});return criteria.concat(Array.from(classes.values()))}
  function findItem(id){return(data.inventoryCriteria||[]).find(item=>item.id===id)||deliveryItems().find(item=>item.id===id)}
  function availableAssets(item){const className=norm(itemName(item));return(data.assets||[]).filter(asset=>!asset.deleted&&!isRetired(asset)&&norm(asset.ubicacion)==='bodega de superficie'&&norm(asset.clase)===className).sort((a,b)=>(Number(assetNumber(a))||Number.MAX_SAFE_INTEGER)-(Number(assetNumber(b))||Number.MAX_SAFE_INTEGER)||assetNumber(a).localeCompare(assetNumber(b),'es',{numeric:true})||(a.serial||'').localeCompare(b.serial||'','es',{numeric:true}))}
  function assetLabel(asset){return[asset.clase,assetNumber(asset)&&`N.º ${assetNumber(asset)}`,asset.marcaActual||asset.marcaInterna||asset.marcaAnterior,asset.serial&&!/no aplica/i.test(asset.serial)?`Serial ${asset.serial}`:''].filter(Boolean).join(' · ')}
  function setupDeliveryForm(){const form=$('#deliveryForm'),itemLabel=form.elements.itemId.closest('label'),quantityLabel=form.elements.quantity.closest('label'),recipientLabel=$('#recipientSearch').closest('label'),submit=form.querySelector('button[type="submit"],button:not([type])');itemLabel.childNodes[0].textContent='SELECCIONE ELEMENTO A ENTREGAR';itemLabel.id='deliveryItemField';quantityLabel.id='deliveryQuantityField';recipientLabel.id='deliveryRecipientField';recipientLabel.childNodes[0].textContent='RECEPTOR';const assetLabelElement=document.createElement('label');assetLabelElement.id='deliveryAssetField';assetLabelElement.hidden=true;assetLabelElement.innerHTML='SELECCIONE EL ACTIVO ESPECÍFICO<select name="assetId" id="deliveryAssetId"><option value="">Seleccionar…</option></select>';itemLabel.after(assetLabelElement);const destination=form.elements.destination.closest('label'),notes=form.elements.notes.closest('label'),newButton=$('#newRecipientBtn'),editButton=$('#editRecipientBtn');form.append(itemLabel,assetLabelElement,quantityLabel,destination,notes,recipientLabel,newButton,editButton,submit);form.elements.itemId.addEventListener('change',updateDeliveryFields)}
  function updateDeliveryFields(){const form=$('#deliveryForm'),item=findItem(form.elements.itemId.value),fixed=item&&isFixedItem(item),assetField=$('#deliveryAssetField'),quantityField=$('#deliveryQuantityField'),assetSelect=$('#deliveryAssetId');assetField.hidden=!fixed;assetField.style.display=fixed?'flex':'none';quantityField.hidden=Boolean(fixed);quantityField.style.display=fixed?'none':'flex';form.elements.quantity.required=!fixed;if(fixed){form.elements.quantity.value='1';const rows=availableAssets(item);assetSelect.required=true;assetSelect.innerHTML=options(rows,assetLabel);if(!rows.length)assetSelect.innerHTML='<option value="">No hay activos disponibles de esta clase</option>'}else{assetSelect.required=false;assetSelect.value='';if(!form.elements.quantity.value)form.elements.quantity.value='1'}}
  function pendingCount(){return['blendingIncomes','blendingDeliveries'].reduce((total,name)=>total+(data[name]||[]).filter(row=>row.syncState==='pending').length,0)}
  function updatePendingBadge(state='idle'){const badge=$('#pendingBadge');if(!badge)return;const count=pendingCount();badge.hidden=false;badge.className='pendingBadge';if(state==='error'){badge.classList.add('error');badge.textContent=count?`⚠ ${count} ${count===1?'registro pendiente':'registros pendientes'}`:'⚠ Error de sincronización';return}if(count){badge.classList.add('pending');badge.textContent=`● ${count} ${count===1?'registro pendiente':'registros pendientes'}`}else{badge.classList.add('synced');badge.textContent='✓ Todo sincronizado'}}
  function render(){const criteria=data.inventoryCriteria||[],stock=new Map((data.inventoryStock||[]).map(row=>[row.itemId,Number(row.quantity)||0]));$('#incomeForm').elements.itemId.innerHTML=options(criteria,item=>`${itemName(item)||'Elemento'}${isFixedItem(item)?' · Activo fijo':` · Disponibles: ${stock.get(item.id)||0}`}`);$('#deliveryForm').elements.itemId.innerHTML=options(deliveryItems(),item=>`${itemName(item)||'Elemento'}${isFixedItem(item)?' · Activo fijo':` · Disponibles: ${stock.get(item.id)||0}`}`);window.SKPlaza?.renderRecipients?.();const identity=user?.nombre||user?.documento||'';$('#userName').textContent=identity;$('#headerUserName').textContent=identity;$('#headerUserRole').textContent=user?.role==='plaza_supervisor'?'SUPERVISOR':'OPERADOR';updateDeliveryFields();updatePendingBadge()}
  async function sync(silent=false){try{$('#syncStatus').textContent='Sincronizando…';updatePendingBadge('syncing');const result=await post({action:'plazaSync',token,data:{blendingIncomes:(data.blendingIncomes||[]).filter(row=>row.syncState==='pending'),blendingDeliveries:(data.blendingDeliveries||[]).filter(row=>row.syncState==='pending')}});data=result.data;localStorage.setItem('skPlazaData',JSON.stringify(data));render();$('#syncStatus').textContent=`Sincronizado · ${new Date().toLocaleString('es-CO')}`}catch(error){$('#syncStatus').textContent='Pendiente de sincronización';updatePendingBadge('error');if(!silent)alert(error.message);if(/sesión venció|sesión no válida/i.test(error.message))logout()}}
  function openApp(){data=JSON.parse(localStorage.getItem('skPlazaData')||'{}');$('#login').hidden=true;$('#app').hidden=false;$('#syncBtn').hidden=false;render();sync(true)}
  function logout(){sessionStorage.removeItem('skPlazaToken');sessionStorage.removeItem('skPlazaUser');location.reload()}
  $('#loginForm').addEventListener('submit',async event=>{event.preventDefault();const fields=new FormData(event.currentTarget);try{$('#loginStatus').textContent='Verificando…';const result=await post({action:'plazaLogin',document:fields.get('document'),pin:fields.get('pin')});token=result.token;user=result.user;sessionStorage.setItem('skPlazaToken',token);sessionStorage.setItem('skPlazaUser',JSON.stringify(user));openApp()}catch(error){$('#loginStatus').textContent=error.message}});
  function movement(form,store){const fields=Object.fromEntries(new FormData(form)),item=findItem(fields.itemId),fixed=item&&isFixedItem(item),quantity=fixed?1:Number(fields.quantity);if(!item)return alert('Selecciona el elemento a entregar.');if(fixed&&!fields.assetId)return alert('Selecciona el activo específico.');if(!(quantity>0))return alert('Cantidad mínima no válida');if(store==='blendingDeliveries'){if(!fields.recipientId)return alert('Busca y selecciona el colaborador que recibe.');if(!fixed){const balance=new Map((data.inventoryStock||[]).map(row=>[row.itemId,Number(row.quantity)||0]));if(quantity>(balance.get(fields.itemId)||0))return alert('La cantidad ingresada supera la disponibilidad')}}const asset=(data.assets||[]).find(row=>row.id===fields.assetId),row={id:uuid(),...fields,quantity,itemName:itemName(item),assetLabel:asset?assetLabel(asset):'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),syncState:'pending'};(data[store]||(data[store]=[])).push(row);if(store==='blendingDeliveries'&&fixed&&asset){asset.ubicacion=fields.destination||'Operación';asset.updatedAt=row.updatedAt;asset.syncState='pending'}localStorage.setItem('skPlazaData',JSON.stringify(data));form.reset();updateDeliveryFields();updatePendingBadge();sync(false)}
  function showView(view){$('nav').hidden=view==='home';document.querySelectorAll('nav button').forEach(button=>button.classList.toggle('active',button.dataset.view===view));document.querySelectorAll('.view').forEach(section=>section.classList.toggle('active',section.id===view))}
  setupDeliveryForm();$('#logoutBtn').textContent='Cerrar sesión';
  window.SKPlaza={post,getData:()=>data,saveData:next=>{data=next;localStorage.setItem('skPlazaData',JSON.stringify(data))},renderRecipients:null};
  $('#incomeForm').addEventListener('submit',event=>{event.preventDefault();movement(event.currentTarget,'blendingIncomes')});$('#deliveryForm').addEventListener('submit',event=>{event.preventDefault();movement(event.currentTarget,'blendingDeliveries')});$('nav').addEventListener('click',event=>{const button=event.target.closest('[data-view]');if(button)showView(button.dataset.view)});$('#home').addEventListener('click',event=>{const button=event.target.closest('[data-home-view]');if(button)showView(button.dataset.homeView)});$('#syncBtn').addEventListener('click',()=>sync(false));$('#logoutBtn').addEventListener('click',logout);showView('home');if(token&&user)openApp();
})();
