const CLOUD_FILE='sk-web-central.json';
function doGet(){return json_({ok:true,service:'SK Web Sync',time:new Date().toISOString()})}
function doPost(e){try{const q=JSON.parse(e.postData.contents||'{}'),expected=PropertiesService.getScriptProperties().getProperty('SK_SYNC_KEY');if(!expected||q.key!==expected)throw new Error('Acceso no autorizado');if(q.action!=='sync'||!q.data)throw new Error('Solicitud no válida');const lock=LockService.getScriptLock();lock.waitLock(30000);try{const id=findFile_(),cloud=id?readFile_(id):{},merged=merge_(cloud,q.data);writeFile_(id,merged);return json_({ok:true,data:merged})}finally{lock.releaseLock()}}catch(e){return json_({ok:false,error:String(e&&e.message||e)})}}
function merge_(cloud,local){const out={schema:6,updatedAt:new Date().toISOString()},names=new Set(Object.keys(cloud||{}).concat(Object.keys(local||{})));names.delete('schema');names.delete('updatedAt');names.forEach(name=>{const map=new Map(),remote=Array.isArray(cloud[name])?cloud[name]:[],device=Array.isArray(local[name])?local[name]:[];remote.forEach(x=>{if(x&&x.id)map.set(x.id,x)});device.forEach(x=>{if(x&&x.id)map.set(x.id,choose_(x,map.get(x.id)))});out[name]=Array.from(map.values())});return out}
function choose_(local,remote){if(!remote)return local;if(!local)return remote;const ls=local.syncState==='seed',rs=remote.syncState==='seed';if(ls!==rs)return ls?remote:local;return stamp_(local)>=stamp_(remote)?local:remote}
function stamp_(x){const n=Date.parse(x.updatedAt||x.createdAt||'');return isNaN(n)?0:n}
function findFile_(){const files=DriveApp.getFilesByName(CLOUD_FILE);return files.hasNext()?files.next().getId():''}
function readFile_(id){return JSON.parse(DriveApp.getFileById(id).getBlob().getDataAsString('UTF-8'))}
function writeFile_(id,data){const body=JSON.stringify(data);if(id){DriveApp.getFileById(id).setContent(body);return id}return DriveApp.createFile(CLOUD_FILE,body,MimeType.PLAIN_TEXT).getId()}
function json_(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
