const CLOUD_FILE='sk-web-central.json';
const PLAZA_READ=['personal','assets','inventoryCriteria','inventoryStock','blendingIncomes','blendingDeliveries'];
const PLAZA_WRITE=['blendingIncomes','blendingDeliveries'];
function doGet(){return json_({ok:true,service:'SK Web Sync',time:new Date().toISOString()})}
function doPost(e){try{const q=JSON.parse(e.postData.contents||'{}');if(q.action==='plazaLogin')return plazaLogin_(q);if(q.action==='plazaSync')return plazaSync_(q);const expected=PropertiesService.getScriptProperties().getProperty('SK_SYNC_KEY');if(!expected||q.key!==expected)throw new Error('Acceso no autorizado');if(q.action!=='sync'||!q.data)throw new Error('Solicitud no válida');const lock=LockService.getScriptLock();lock.waitLock(30000);try{const id=findFile_(),cloud=id?readFile_(id):{},merged=merge_(cloud,q.data);writeFile_(id,merged);return json_({ok:true,data:merged})}finally{lock.releaseLock()}}catch(e){return json_({ok:false,error:String(e&&e.message||e)})}}

function plazaLogin_(q){const document=String(q.document||'').trim(),pin=String(q.pin||'');if(!document||!pin)throw new Error('Documento y PIN son obligatorios');const id=findFile_(),cloud=id?readFile_(id):{},person=(cloud.personal||[]).find(x=>String(x.documento||'').trim()===document&&!x.deleted);if(!person||person.plazaEnabled!==true||!person.pinHash)throw new Error('Usuario no habilitado para Plaza Blending');if(!safeEqual_(String(person.pinHash),hashPin_(document,pin)))throw new Error('Documento o PIN incorrecto');const role=person.plazaRole==='supervisor'?'plaza_supervisor':'plaza_operator',expires=Date.now()+12*60*60*1000,payload=[document,role,expires].join('|'),token=Utilities.base64EncodeWebSafe(payload,false)+'.'+sign_(payload);return json_({ok:true,token,user:{id:person.id,documento:document,nombre:person.nombre||'',role:role},expiresAt:new Date(expires).toISOString()})}
function plazaSync_(q){const auth=verifyToken_(q.token),incoming=q.data||{},lock=LockService.getScriptLock();lock.waitLock(30000);try{const id=findFile_(),cloud=id?readFile_(id):{},allowed={},stock=new Map((cloud.inventoryStock||[]).filter(x=>x&&x.itemId).map(x=>[x.itemId,Object.assign({},x)]));PLAZA_WRITE.forEach(name=>{const existing=new Set((cloud[name]||[]).map(x=>x&&x.id));allowed[name]=(Array.isArray(incoming[name])?incoming[name]:[]).filter(x=>x&&x.syncState==='pending'&&!existing.has(x.id)).map(x=>{const row=stampActor_(x,auth),qty=Number(row.quantity);if(!(qty>0)||!row.itemId)throw new Error('Movimiento incompleto');const current=stock.get(row.itemId)||{id:'stock-'+row.itemId,itemId:row.itemId,quantity:0},next=(Number(current.quantity)||0)+(name==='blendingIncomes'?qty:-qty);if(next<0)throw new Error('La cantidad ingresada supera la disponibilidad');current.quantity=next;current.updatedAt=new Date().toISOString();stock.set(row.itemId,current);row.syncState='synced';return row})});allowed.inventoryStock=Array.from(stock.values());const merged=merge_(cloud,allowed);writeFile_(id,merged);const view={schema:merged.schema,updatedAt:merged.updatedAt};PLAZA_READ.forEach(name=>view[name]=Array.isArray(merged[name])?merged[name]:[]);view.personal=view.personal.map(x=>({id:x.id,documento:x.documento||'',nombre:x.nombre||'',area:x.area||'',cargo:x.cargo||'',empresa:x.empresa||'',deleted:!!x.deleted}));return json_({ok:true,data:view})}finally{lock.releaseLock()}}
function stampActor_(x,auth){if(!x||!x.id)throw new Error('Movimiento sin identificador');const out=Object.assign({},x);out.actorDocument=auth.document;out.actorRole=auth.role;delete out.pinHash;delete out.plazaEnabled;delete out.plazaRole;return out}
function hashPin_(document,pin){const salt=PropertiesService.getScriptProperties().getProperty('SK_AUTH_SALT');if(!salt)throw new Error('Falta configurar SK_AUTH_SALT');return hex_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,document+'|'+pin+'|'+salt,Utilities.Charset.UTF_8))}
function sign_(payload){const secret=PropertiesService.getScriptProperties().getProperty('SK_AUTH_SECRET');if(!secret)throw new Error('Falta configurar SK_AUTH_SECRET');return Utilities.base64EncodeWebSafe(Utilities.computeHmacSha256Signature(payload,secret),false)}
function verifyToken_(token){const bits=String(token||'').split('.');if(bits.length!==2)throw new Error('Sesión no válida');const payload=Utilities.newBlob(Utilities.base64DecodeWebSafe(bits[0])).getDataAsString(),parts=payload.split('|');if(parts.length!==3||!safeEqual_(bits[1],sign_(payload))||Number(parts[2])<Date.now())throw new Error('La sesión venció');if(parts[1]!=='plaza_operator'&&parts[1]!=='plaza_supervisor')throw new Error('Permiso no válido');return{document:parts[0],role:parts[1]}}
function safeEqual_(a,b){a=String(a);b=String(b);if(a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0}
function hex_(bytes){return bytes.map(x=>(x<0?x+256:x).toString(16).padStart(2,'0')).join('')}
function enablePlazaUser(document,pin,role){document=String(document||'').trim();pin=String(pin||'');if(!document||!pin)throw new Error('Documento y PIN son obligatorios');const lock=LockService.getScriptLock();lock.waitLock(30000);try{const id=findFile_(),cloud=id?readFile_(id):{},person=(cloud.personal||[]).find(x=>String(x.documento||'').trim()===document&&!x.deleted);if(!person)throw new Error('El documento no existe en Personal');person.plazaEnabled=true;person.plazaRole=role==='supervisor'?'supervisor':'operator';person.pinHash=hashPin_(document,pin);person.updatedAt=new Date().toISOString();writeFile_(id,cloud);return 'Usuario de Plaza Blending habilitado: '+document}finally{lock.releaseLock()}}
function merge_(cloud,local){const out={schema:6,updatedAt:new Date().toISOString()},names=new Set(Object.keys(cloud||{}).concat(Object.keys(local||{})));names.delete('schema');names.delete('updatedAt');names.forEach(name=>{const map=new Map(),remote=Array.isArray(cloud[name])?cloud[name]:[],device=Array.isArray(local[name])?local[name]:[];remote.forEach(x=>{if(x&&x.id)map.set(x.id,x)});device.forEach(x=>{if(x&&x.id)map.set(x.id,choose_(x,map.get(x.id)))});out[name]=Array.from(map.values())});return out}
function choose_(local,remote){if(!remote)return local;if(!local)return remote;const ls=local.syncState==='seed',rs=remote.syncState==='seed';if(ls!==rs)return ls?remote:local;return stamp_(local)>=stamp_(remote)?local:remote}
function stamp_(x){const n=Date.parse(x.updatedAt||x.createdAt||'');return isNaN(n)?0:n}
function api_(url,options){const r=UrlFetchApp.fetch(url,Object.assign({muteHttpExceptions:true,headers:{Authorization:'Bearer '+ScriptApp.getOAuthToken()}},options||{})),code=r.getResponseCode();if(code<200||code>=300)throw new Error('Google Drive respondió '+code+': '+r.getContentText());return r}
function findFile_(){const q=encodeURIComponent("name='"+CLOUD_FILE+"' and trashed=false"),files=JSON.parse(api_('https://www.googleapis.com/drive/v3/files?spaces=appDataFolder&q='+q+'&fields=files(id)&pageSize=1').getContentText()).files||[];return files.length?files[0].id:''}
function readFile_(id){return JSON.parse(api_('https://www.googleapis.com/drive/v3/files/'+id+'?alt=media').getContentText())}
function writeFile_(id,data){const body=JSON.stringify(data);if(id){api_('https://www.googleapis.com/upload/drive/v3/files/'+id+'?uploadType=media',{method:'patch',contentType:'application/json',payload:body});return id}const boundary='skweb'+Date.now(),multipart='--'+boundary+'\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n'+JSON.stringify({name:CLOUD_FILE,parents:['appDataFolder'],mimeType:'application/json'})+'\r\n--'+boundary+'\r\nContent-Type: application/json\r\n\r\n'+body+'\r\n--'+boundary+'--',r=api_('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id',{method:'post',contentType:'multipart/related; boundary='+boundary,payload:multipart});return JSON.parse(r.getContentText()).id}
function json_(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
