const CLOUD_FILE='sk-web-central.json';
const PLAZA_READ=['personal','assets','inventoryCriteria','inventoryStock','blendingIncomes','blendingDeliveries'];
const PLAZA_WRITE=['blendingIncomes','blendingDeliveries'];
function doGet(){return json_({ok:true,service:'SK Web Sync',time:new Date().toISOString()})}
function doPost(e){try{const q=JSON.parse(e.postData.contents||'{}');if(q.action==='plazaLogin')return plazaLogin_(q);if(q.action==='plazaSync')return plazaSync_(q);if(q.action==='plazaCollaborator')return plazaCollaborator_(q);const expected=PropertiesService.getScriptProperties().getProperty('SK_SYNC_KEY');if(!expected||q.key!==expected)throw new Error('Acceso no autorizado');if(q.action==='plazaUserAdmin')return plazaUserAdmin_(q);if(q.action!=='sync'||!q.data)throw new Error('Solicitud no válida');const lock=LockService.getScriptLock();lock.waitLock(30000);try{const id=findFile_(),cloud=id?readFile_(id):{},merged=merge_(cloud,q.data);writeFile_(id,merged);return json_({ok:true,data:merged})}finally{lock.releaseLock()}}catch(e){return json_({ok:false,error:String(e&&e.message||e)})}}

function plazaLogin_(q){const document=String(q.document||'').trim(),pin=String(q.pin||'');if(!document||!pin)throw new Error('Documento y PIN son obligatorios');const id=findFile_(),cloud=id?readFile_(id):{},person=(cloud.personal||[]).find(x=>String(x.documento||'').trim()===document&&!x.deleted);if(!person||person.plazaEnabled!==true||!person.pinHash)throw new Error('Usuario no habilitado para Plaza Blending');if(!safeEqual_(String(person.pinHash),hashPin_(document,pin)))throw new Error('PIN incorrecto');const role=person.plazaRole==='supervisor'?'plaza_supervisor':'plaza_operator',expires=Date.now()+12*60*60*1000,payload=[document,role,expires].join('|'),token=Utilities.base64EncodeWebSafe(payload)+'.'+sign_(payload);return json_({ok:true,token,user:{id:person.id,documento:document,nombre:person.nombre||'',role:role},expiresAt:new Date(expires).toISOString()})}
function plazaSync_(q){
  const auth=verifyToken_(q.token),incoming=q.data||{},lock=LockService.getScriptLock();
  lock.waitLock(30000);
  try{
    const id=findFile_(),cloud=id?readFile_(id):{},allowed={},stock=new Map((cloud.inventoryStock||[]).filter(x=>x&&x.itemId).map(x=>[x.itemId,Object.assign({},x)]));
    PLAZA_WRITE.forEach(name=>{
      const existing=new Set((cloud[name]||[]).map(x=>x&&x.id));
      allowed[name]=(Array.isArray(incoming[name])?incoming[name]:[]).filter(x=>x&&x.syncState==='pending'&&!existing.has(x.id)).map(x=>{
        const row=stampActor_(x,auth),qty=Number(row.quantity);
        if(!(qty>0)||!row.itemId)throw new Error('Movimiento incompleto');
        if(name==='blendingDeliveries'&&row.assetId){
          const asset=(cloud.assets||[]).find(x=>x&&x.id===row.assetId&&!x.deleted);
          if(!asset)throw new Error('El activo seleccionado no existe');
          if(String(asset.ubicacion||'').toLowerCase()!=='bodega de superficie')throw new Error('El activo ya no está disponible en Bodega de Superficie');
          asset.ubicacion=row.destination||'Operación';asset.updatedAt=new Date().toISOString();
        }else{
          const current=stock.get(row.itemId)||{id:'stock-'+row.itemId,itemId:row.itemId,quantity:0},next=(Number(current.quantity)||0)+(name==='blendingIncomes'?qty:-qty);
          if(next<0)throw new Error('La cantidad ingresada supera la disponibilidad');
          current.quantity=next;current.updatedAt=new Date().toISOString();stock.set(row.itemId,current);
        }
        row.syncState='synced';return row;
      });
    });
    allowed.inventoryStock=Array.from(stock.values());
    const merged=merge_(cloud,allowed);writeFile_(id,merged);const view={schema:merged.schema,updatedAt:merged.updatedAt};
    PLAZA_READ.forEach(name=>view[name]=Array.isArray(merged[name])?merged[name]:[]);view.personal=view.personal.map(x=>publicPerson_(x));
    return json_({ok:true,data:view});
  }finally{lock.releaseLock()}
}
function stampActor_(x,auth){if(!x||!x.id)throw new Error('Movimiento sin identificador');const out=Object.assign({},x);out.actorDocument=auth.document;out.actorRole=auth.role;delete out.pinHash;delete out.plazaEnabled;delete out.plazaRole;return out}
function hashPin_(document,pin){const salt=PropertiesService.getScriptProperties().getProperty('SK_AUTH_SALT');if(!salt)throw new Error('Falta configurar SK_AUTH_SALT');return hex_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,document+'|'+pin+'|'+salt,Utilities.Charset.UTF_8))}
function sign_(payload){const secret=PropertiesService.getScriptProperties().getProperty('SK_AUTH_SECRET');if(!secret)throw new Error('Falta configurar SK_AUTH_SECRET');return Utilities.base64EncodeWebSafe(Utilities.computeHmacSha256Signature(payload,secret))}
function verifyToken_(token){const bits=String(token||'').split('.');if(bits.length!==2)throw new Error('Sesión no válida');const payload=Utilities.newBlob(Utilities.base64DecodeWebSafe(bits[0])).getDataAsString(),parts=payload.split('|');if(parts.length!==3||!safeEqual_(bits[1],sign_(payload))||Number(parts[2])<Date.now())throw new Error('La sesión venció');if(parts[1]!=='plaza_operator'&&parts[1]!=='plaza_supervisor')throw new Error('Permiso no válido');return{document:parts[0],role:parts[1]}}
function safeEqual_(a,b){a=String(a);b=String(b);if(a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0}
function hex_(bytes){return bytes.map(x=>(x<0?x+256:x).toString(16).padStart(2,'0')).join('')}
function enablePlazaUser(document,pin,role){document=String(document||'').trim();pin=String(pin||'');if(!document||!pin)throw new Error('Documento y PIN son obligatorios');const lock=LockService.getScriptLock();lock.waitLock(30000);try{const id=findFile_(),cloud=id?readFile_(id):{},person=(cloud.personal||[]).find(x=>String(x.documento||'').trim()===document&&!x.deleted);if(!person)throw new Error('El documento no existe en Personal');person.plazaEnabled=true;person.plazaRole=role==='supervisor'?'supervisor':'operator';person.pinHash=hashPin_(document,pin);person.updatedAt=new Date().toISOString();writeFile_(id,cloud);return 'Usuario de Plaza Blending habilitado: '+document}finally{lock.releaseLock()}}
function plazaUserAdmin_(q){const document=String(q.document||'').trim(),enabled=q.enabled===true,pin=String(q.pin||''),role=q.role==='supervisor'?'supervisor':'operator';if(!document)throw new Error('Selecciona un colaborador');const lock=LockService.getScriptLock();lock.waitLock(30000);try{const id=findFile_(),cloud=id?readFile_(id):{},person=(cloud.personal||[]).find(x=>String(x.documento||'').trim()===document&&!x.deleted);if(!person)throw new Error('El colaborador no existe en la base central');if(enabled){if(pin)person.pinHash=hashPin_(document,pin);if(!person.pinHash)throw new Error('Escribe un PIN para habilitar el acceso');person.plazaEnabled=true;person.plazaRole=role}else{person.plazaEnabled=false;delete person.pinHash;delete person.plazaRole}person.updatedAt=new Date().toISOString();writeFile_(id,cloud);return json_({ok:true,user:{id:person.id,documento:document,nombre:person.nombre||'',plazaEnabled:person.plazaEnabled===true,plazaRole:person.plazaRole||''}})}finally{lock.releaseLock()}}
function plazaCollaborator_(q){const auth=verifyToken_(q.token),input=q.collaborator||{},document=String(input.documento||'').trim(),primerNombre=String(input.primerNombre||'').trim(),segundoNombre=String(input.segundoNombre||'').trim(),primerApellido=String(input.primerApellido||'').trim(),segundoApellido=String(input.segundoApellido||'').trim(),nombre=[primerNombre,segundoNombre,primerApellido,segundoApellido].filter(Boolean).join(' '),empresa=String(input.empresa||'').trim(),area=String(input.area||'').trim(),cargo=String(input.cargo||'No informado').trim()||'No informado',telefono=String(input.telefono||'').trim();if(!document||!primerNombre||!primerApellido||!empresa||!area)throw new Error('Documento, primer nombre, primer apellido, empresa y área son obligatorios');const lock=LockService.getScriptLock();lock.waitLock(30000);try{const id=findFile_(),cloud=id?readFile_(id):{},rows=Array.isArray(cloud.personal)?cloud.personal:(cloud.personal=[]),existing=rows.find(x=>String(x.documento||'').trim()===document&&!x.deleted);if(existing&&!q.update)return json_({ok:true,exists:true,user:publicPerson_(existing)});const now=new Date().toISOString(),person=existing||{id:'PERSONAL-PLAZA-'+Utilities.getUuid(),createdAt:now};Object.assign(person,{documento:document,primerNombre:primerNombre,segundoNombre:segundoNombre,primerApellido:primerApellido,segundoApellido:segundoApellido,nombre:nombre,empresa:empresa,area:area,cargo:cargo,telefono:telefono,deleted:false,updatedAt:now,syncState:'synced',registeredBy:auth.document});if(!existing)rows.push(person);cloud.personal=dedupePersonal_(rows);writeFile_(id,cloud);return json_({ok:true,exists:false,user:publicPerson_(person)})}finally{lock.releaseLock()}}
function publicPerson_(x){return{id:x.id,documento:x.documento||'',primerNombre:x.primerNombre||'',segundoNombre:x.segundoNombre||'',primerApellido:x.primerApellido||'',segundoApellido:x.segundoApellido||'',nombre:x.nombre||'',empresa:x.empresa||'',area:x.area||'',cargo:x.cargo||'No informado',telefono:x.telefono||'',deleted:!!x.deleted}}
function merge_(cloud,local){const out={schema:6,updatedAt:new Date().toISOString()},names=new Set(Object.keys(cloud||{}).concat(Object.keys(local||{})));names.delete('schema');names.delete('updatedAt');names.forEach(name=>{const map=new Map(),remote=Array.isArray(cloud[name])?cloud[name]:[],device=Array.isArray(local[name])?local[name]:[];remote.forEach(x=>{if(x&&x.id)map.set(x.id,x)});device.forEach(x=>{if(x&&x.id)map.set(x.id,choose_(x,map.get(x.id)))});out[name]=Array.from(map.values())});if(Array.isArray(out.personal))out.personal=dedupePersonal_(out.personal);return out}
function dedupePersonal_(rows){const map=new Map();rows.forEach(x=>{if(!x||!x.id)return;const document=String(x.documento||'').trim(),key=document?'doc:'+document:'id:'+x.id,old=map.get(key);if(!old){map.set(key,x);return}const chosen=choose_(x,old);map.set(key,Object.assign({},old,chosen,{id:old.id||chosen.id}))});return Array.from(map.values())}
function choose_(local,remote){if(!remote)return local;if(!local)return remote;const ls=local.syncState==='seed',rs=remote.syncState==='seed';if(ls!==rs)return ls?remote:local;return stamp_(local)>=stamp_(remote)?local:remote}
function stamp_(x){const n=Date.parse(x.updatedAt||x.createdAt||'');return isNaN(n)?0:n}
function findFile_(){const files=DriveApp.getFilesByName(CLOUD_FILE);return files.hasNext()?files.next().getId():''}
function readFile_(id){return JSON.parse(DriveApp.getFileById(id).getBlob().getDataAsString('UTF-8'))}
function writeFile_(id,data){const body=JSON.stringify(data);if(id){DriveApp.getFileById(id).setContent(body);return id}return DriveApp.createFile(CLOUD_FILE,body,MimeType.PLAIN_TEXT).getId()}
function json_(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
